/**
 * Lights Out: a solo skill wager, or free practice, any time.
 *
 * Tapping a tile flips it and its orthogonal neighbors; clear every light and
 * cash out a multiple of the wager, same model as ante-up-memory.ts. Same
 * shape as Memory Match's own wager, and for the same reason: this board has
 * no natural loss condition either (every board here is generated by
 * scrambling an all-off grid, so it is always solvable), so a move cap is the
 * invented forfeit condition a wager needs to have real risk. See
 * ante-up-memory.ts's header for why that isn't optional.
 */

import type { RandomInt } from "@/lib/game/deck";

export const MIN_ANTE_UP_WAGER = 500;

export const LIGHTS_OUT_SIZE = 5;
const CELLS = LIGHTS_OUT_SIZE * LIGHTS_OUT_SIZE;
/** How many random taps scramble a fresh board. Also this board's par. */
const SCRAMBLE_TAPS = 8;
/** Moves a wagered attempt may take before it forfeits. Restated per game; see ante-up-memory.ts's ANTE_UP_MEMORY_MAX_TURNS. */
export const LIGHTS_OUT_MAX_MOVES = 20;

function neighbors(index: number): number[] {
  const row = Math.floor(index / LIGHTS_OUT_SIZE);
  const col = index % LIGHTS_OUT_SIZE;
  const result = [index];
  if (row > 0) result.push(index - LIGHTS_OUT_SIZE);
  if (row < LIGHTS_OUT_SIZE - 1) result.push(index + LIGHTS_OUT_SIZE);
  if (col > 0) result.push(index - 1);
  if (col < LIGHTS_OUT_SIZE - 1) result.push(index + 1);
  return result;
}

function toggle(lights: boolean[], index: number): boolean[] {
  const next = [...lights];
  for (const i of neighbors(index)) next[i] = !next[i];
  return next;
}

/** A fresh, always-solvable board: every tap is its own inverse, so scrambling from all-off guarantees a solution exists. */
function scrambleBoard(randomInt: RandomInt): boolean[] {
  let lights = Array<boolean>(CELLS).fill(false);
  let taps = 0;
  // A scramble that happens to cancel itself back to all-off would deal a
  // won board, so re-roll until at least one light is on.
  while (taps < 1 || lights.every((on) => !on)) {
    lights = Array<boolean>(CELLS).fill(false);
    for (let i = 0; i < SCRAMBLE_TAPS; i++) lights = toggle(lights, randomInt(CELLS));
    taps = SCRAMBLE_TAPS;
  }
  return lights;
}

/** Win-only payout multiplier, keyed by moves taken. See wagerMultiplierForTurns's header for why the slow rungs pay under 1x on purpose. */
export function wagerMultiplierForMoves(moves: number): number {
  if (moves <= SCRAMBLE_TAPS) return 3;
  if (moves <= 12) return 2;
  if (moves <= 16) return 1.3;
  if (moves <= LIGHTS_OUT_MAX_MOVES) return 0.8;
  return 0;
}

export type BrainLightsOutStatus = "active" | "won" | "lost";

export interface BrainLightsOutAttempt {
  wager: number;
  lights: boolean[];
  moves: number;
  status: BrainLightsOutStatus;
  startedAt: string;
  finishedAt: string | null;
}

export function startBrainLightsOut(randomInt: RandomInt, wager: number, now: Date): BrainLightsOutAttempt {
  return {
    wager,
    lights: scrambleBoard(randomInt),
    moves: 0,
    status: "active",
    startedAt: now.toISOString(),
    finishedAt: null,
  };
}

/** Taps one tile. Clearing the board wins; exceeding the move cap forfeits. */
export function tapBrainLightsOut(attempt: BrainLightsOutAttempt, index: number, now: Date): BrainLightsOutAttempt {
  if (attempt.status !== "active" || index < 0 || index >= CELLS) return attempt;

  const lights = toggle(attempt.lights, index);
  const moves = attempt.moves + 1;
  const cleared = lights.every((on) => !on);
  if (cleared) return { ...attempt, lights, moves, status: "won", finishedAt: now.toISOString() };
  // >=, not >: see ante-up-memory.ts's flipAnteUpMemoryTile for why the move
  // that reaches the cap is the one that forfeits, not the one after it.
  if (moves >= LIGHTS_OUT_MAX_MOVES) return { ...attempt, lights, moves, status: "lost", finishedAt: now.toISOString() };
  return { ...attempt, lights, moves };
}

export function resignBrainLightsOut(attempt: BrainLightsOutAttempt, now: Date): BrainLightsOutAttempt {
  if (attempt.status !== "active") return attempt;
  return { ...attempt, status: "lost", finishedAt: now.toISOString() };
}

export function brainLightsOutPayout(attempt: Pick<BrainLightsOutAttempt, "wager" | "status" | "moves">): number {
  if (attempt.status !== "won") return 0;
  return Math.round(attempt.wager * wagerMultiplierForMoves(attempt.moves));
}

export interface BrainLightsOutSnapshot {
  id: string;
  wager: number;
  version: number;
  status: BrainLightsOutStatus;
  size: number;
  lights: boolean[];
  moves: number;
  maxMoves: number;
  payout: number;
}

export function toBrainLightsOutSnapshot(
  attempt: BrainLightsOutAttempt,
  meta: { id: string; version: number },
): BrainLightsOutSnapshot {
  return {
    id: meta.id,
    wager: attempt.wager,
    version: meta.version,
    status: attempt.status,
    size: LIGHTS_OUT_SIZE,
    lights: [...attempt.lights],
    moves: attempt.moves,
    maxMoves: LIGHTS_OUT_MAX_MOVES,
    payout: brainLightsOutPayout(attempt),
  };
}
