"use client";

import clsx from "clsx";
import type { DuelBoardProps } from "./duel-shell";
import {
  BOARD_SIDE,
  BOARD_SQUARES,
  cellOwner,
  colOf,
  rowOf,
  type OthelloCell,
  type OthelloSnapshot,
} from "@/lib/pvp/othello";

/**
 * The Othello board.
 *
 * Renders the snapshot and sends one square; it decides nothing. Every
 * legality question is answered by `state.legalMoves`, generated by the engine
 * on the server, the same contract checkers-board.tsx follows. A client-side
 * rule set would be a second definition of Othello, and the two would disagree
 * on exactly the hard cases (a ray that closes on the far edge, a move that
 * flips in six directions at once, whose turn it is after a pass).
 *
 * A move is a single tap, so there is no half-assembled state to hold: unlike
 * a checkers jump chain, one square IS the whole turn. What the board does add
 * is a preview of what a square would turn over, from the flip lists the
 * engine already sent, since a player who cannot see that is reduced to
 * tapping squares to find out.
 */

/** Files and ranks from seat 0's side, for the screen-reader label. */
const FILES = "abcdefgh";

function squareName(square: number): string {
  return `${FILES[colOf(square)]}${BOARD_SIDE - rowOf(square)}`;
}

function discName(cell: OthelloCell): string {
  const owner = cellOwner(cell);
  if (owner === null) return "empty";
  return owner === 0 ? "black" : "white";
}

/**
 * mm:ss.
 *
 * Ceiling rather than floor, so a clock reads "0:01" until the second it
 * actually runs out. A display showing 0:00 while a move is still legal is the
 * kind of thing a player reports as a lost game.
 */
function clockLabel(ms: number): string {
  const seconds = Math.max(0, Math.ceil(ms / 1000));
  return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`;
}

export function OthelloBoard({ state, yourSeat, busy, onMove }: DuelBoardProps<OthelloSnapshot>) {
  const legal = state.legalMoves;

  // Your turn is exactly "the server sent me moves"; there is no second
  // opinion about whose turn it is, and there must not be one.
  const yourTurn = legal.length > 0;
  const interactive = yourTurn && !busy;

  const playable = new Map(legal.map((move) => [move.square, move.flips]));

  // Seat 1 plays from the far side, so their view is turned through 180
  // degrees on both axes rather than mirrored on one: a board flipped only by
  // rows would put the diagonals the wrong way round.
  const flipped = yourSeat === 1;
  const order: number[] = [];
  for (let index = 0; index < BOARD_SQUARES; index += 1) {
    order.push(flipped ? BOARD_SQUARES - 1 - index : index);
  }

  const yourDiscs = state.discs[yourSeat];
  const theirDiscs = state.discs[yourSeat === 0 ? 1 : 0];
  const yourClock = state.clocks[yourSeat];
  const theirClock = state.clocks[yourSeat === 0 ? 1 : 0];
  // Seat 0 is always black (see lib/pvp/othello.ts); restated here only for
  // the clock-row labels, not as a second copy of the rule.
  const yourColor = yourSeat === 0 ? "Black" : "White";
  const opponentColor = yourSeat === 0 ? "White" : "Black";

  // The best square on offer, for the hint line. Not advice about strategy --
  // the biggest flip is often a bad move in Othello -- only a statement of what
  // is available, so a player can tell a quiet board from a busy one.
  const bestFlip = legal.reduce((most, move) => Math.max(most, move.flips.length), 0);

  return (
    <div className="ot">
      <div className="ot-clock-row">
        <span className="ot-side">Opponent · {opponentColor}</span>
        <span className="ot-discs">{theirDiscs}</span>
        <span className={clsx("ot-clock", !yourTurn && "ot-clock-running")}>
          {clockLabel(theirClock)}
        </span>
      </div>

      <div className="ot-board" aria-label="Othello board">
        {order.map((square) => {
          const cell = state.board[square] as OthelloCell;
          const owner = cellOwner(cell);
          const flips = playable.get(square);
          const clickable = interactive && flips !== undefined;

          return (
            <button
              key={square}
              type="button"
              className={clsx(
                "ot-square",
                flips !== undefined && "ot-square-legal",
                owner !== null && "ot-square-taken",
              )}
              disabled={!clickable}
              onClick={() => onMove({ square })}
              aria-label={
                `${squareName(square)}, ${discName(cell)}` +
                (flips !== undefined ? `, playable, turns over ${flips.length}` : "")
              }
            >
              {owner !== null ? (
                <span
                  className={clsx(
                    "ot-disc",
                    owner === 0 ? "ot-disc-black" : "ot-disc-white",
                    owner === yourSeat && "ot-disc-yours",
                  )}
                  aria-hidden="true"
                />
              ) : (
                flips !== undefined && (
                  // How many discs this square would turn over, sat where the
                  // disc would land. The number is the whole point of the
                  // marker: an unlabelled dot says "legal" and nothing else.
                  <span className="ot-ghost" aria-hidden="true">{flips.length}</span>
                )
              )}
            </button>
          );
        })}
      </div>

      <div className="ot-clock-row">
        <span className="ot-side">You · {yourColor}</span>
        <span className="ot-discs">{yourDiscs}</span>
        <span className={clsx("ot-clock", yourTurn && "ot-clock-running")}>
          {clockLabel(yourClock)}
        </span>
      </div>

      {/* The pass is the rule a new player is most surprised by: their turn
          simply does not arrive, and nothing on screen says why. Saying it
          here is cheaper than the support message. */}
      <p className={clsx("ot-status", state.passed && "ot-status-passed")}>
        {state.outcome
          ? state.outcome.reason
          : state.passed && yourTurn
            ? "They had no legal move, so it is your turn again."
            : state.passed
              ? "You had no legal move, so it went back to them."
              : !yourTurn
                ? "Waiting for your opponent…"
                : bestFlip > 0
                  ? `Your move — ${legal.length} square${legal.length === 1 ? "" : "s"} open, up to ${bestFlip} to turn.`
                  : "Your move."}
      </p>
    </div>
  );
}
