import type { Metadata, Viewport } from "next";
import "./globals.css";

const TITLE = "StackChips - Play Free Texas Hold’em";
const DESCRIPTION =
  "Six-max Texas Hold’em, PvP duels, and cribbage tables played with Gold — an in-app currency with no cash value. No pure-chance games, no rake.";

export const metadata: Metadata = {
  metadataBase: new URL("https://stackchips.app"),
  title: TITLE,
  description: DESCRIPTION,
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "StackChips",
  },
  // The opengraph-image.tsx file convention supplies the image itself; this
  // just fills in the text half of the card so a shared link reads right
  // before the image even loads (and for the platforms that skip images).
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: "https://stackchips.app",
    siteName: "StackChips",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  // Kept in step with app/manifest.ts and the html/body base: this is the
  // colour the browser paints its own chrome with, so a stale value shows up
  // as a differently-coloured band above the page.
  themeColor: "#0f1218",
};

/*
 * The Adsterra loader used to sit in this body, as two <Script strategy=
 * "afterInteractive"> tags. It was removed rather than moved, and it is worth
 * knowing why before anyone puts it back.
 *
 * That unit's invoke script `document.write`s its markup at the position of
 * its own <script> tag. document.write is only defined during the initial
 * parse; called on a document that has already closed -- which is exactly what
 * "afterInteractive" means, since Next appends the tag after hydration -- it
 * implicitly calls document.open() and BLANKS THE PAGE. In an app whose entire
 * UI is one client tree, that is the table disappearing mid-hand.
 *
 * The unit now renders through components/ads/adsterra-slot.tsx, which gives
 * it its own sandboxed srcdoc document, so its document.write happens during a
 * parse (legal) in a document that is not ours (contained). The rewarded-ad
 * modal mounts it. Anything else wanting a banner should mount that component
 * too; nothing should reintroduce a loader here.
 */
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/*
         * iOS has no equivalent of Android/Chrome's automatic manifest-driven
         * splash (icon + background_color painted the instant the icon is
         * tapped) -- an installed StackChips just sits on a blank white
         * screen for as long as the page takes to load and hydrate, unlike
         * an app that shows its own logo immediately. These links are that
         * splash: one exact-size PNG per device/pixel-ratio bucket, matched
         * via `media`, generated by scripts/generate-startup-images.mjs
         * (re-run it if public/brand/stackchips-logo.png ever changes -- this
         * block is pasted straight from its output). Metadata.icons doesn't
         * cover apple-touch-startup-image's `media` attribute, hence a plain
         * <link> here instead of the metadata API.
         */}
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-640x1136.png" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-750x1334.png" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-1242x2208.png" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-1125x2436.png" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-828x1792.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-1242x2688.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-1170x2532.png" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-1284x2778.png" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-1179x2556.png" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-1290x2796.png" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-1206x2622.png" media="(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/apple-splash-1320x2868.png" media="(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
      </head>
      <body>{children}</body>
    </html>
  );
}
