/**
 * Where the hoe may break a bed on the Homestead.
 *
 * ANY GRASS, not two paddocks. The hoe used to work only inside two marked
 * patches by the house and in the Crop Fields; everywhere else a tap just
 * walked. Now a bed can go on any grass square with nothing standing on it,
 * which is a fact only the map knows -- so the map writes it down
 * (./homestead-ground.ts, generated by art/stackacres-td/rich/export_rich.py)
 * and this reads it. The server checks a bed against this before it creates
 * one, so the tapped square is never taken on trust.
 *
 * ONE GRID. A bed is stored as a soil tile (tx, ty), and every soil tile sits
 * on exactly one Homestead map tile, `SOIL_TO_MAP` away. There used to be two
 * grids -- one for the Crop Fields, one for the paddocks, with origins chosen
 * far apart so they could never touch -- because a bed could only exist in one
 * of those two places. With a bed allowed anywhere, two grids would give the
 * same square two names. The Crop Fields' grid is the one kept, so every bed
 * already dug out there keeps its coordinates; see the migration
 * 20260923120000_stackacres_one_soil_grid.sql for the paddock beds that moved.
 *
 * Pure and renderer-free: the server imports this.
 */

import { HOMESTEAD_HOEABLE_ROWS, HOMESTEAD_MAP_HEIGHT, HOMESTEAD_MAP_WIDTH, HOMESTEAD_WILD_ROWS } from "./homestead-ground";
import { SOIL_TILE } from "./soil";
import { CROP_FIELD_BEDS } from "./world";

/** Map tile soil tile (-16, -16), the corner of `CROP_FIELD_BEDS`, is drawn on. It only fixes
 *  where the shared grid sits: soil tile (0, 0) lands on map tile (32, 22), the middle of the map. */
export const FIELD_MAP_TILE = { tx: 16, ty: 6 } as const;

/**
 * Soil tile (tx, ty) sits on Homestead map tile (tx + SOIL_TO_MAP.tx, ty + SOIL_TO_MAP.ty).
 *
 * Derived from where the Crop Fields are drawn rather than written as a bare
 * pair of numbers, so moving the field on the map moves every bed with it.
 */
export const SOIL_TO_MAP = {
  tx: FIELD_MAP_TILE.tx - CROP_FIELD_BEDS.x / SOIL_TILE,
  ty: FIELD_MAP_TILE.ty - CROP_FIELD_BEDS.y / SOIL_TILE,
} as const;

/** Whether the hoe may break a bed on this Homestead map tile. Off the map is never hoeable. */
export function isHoeableMapTile(mx: number, my: number): boolean {
  if (mx < 0 || my < 0 || mx >= HOMESTEAD_MAP_WIDTH || my >= HOMESTEAD_MAP_HEIGHT) return false;
  return HOMESTEAD_HOEABLE_ROWS[my]?.[mx] === "1";
}

/** Whether this map tile is out in the wild land round the yard, where the Crop Fields' overgrowth stands. */
export function isWildMapTile(mx: number, my: number): boolean {
  if (mx < 0 || my < 0 || mx >= HOMESTEAD_MAP_WIDTH || my >= HOMESTEAD_MAP_HEIGHT) return false;
  return HOMESTEAD_WILD_ROWS[my]?.[mx] === "1";
}

/** Whether a bed on this soil tile is out in the wild land. The first one is the Crop Fields milestone. */
export function isWildSoilTile(tx: number, ty: number): boolean {
  const { mx, my } = soilToMapTile(tx, ty);
  return isWildMapTile(mx, my);
}

/** The Homestead map tile a soil tile is drawn on. */
export function soilToMapTile(tx: number, ty: number): { mx: number; my: number } {
  return { mx: tx + SOIL_TO_MAP.tx, my: ty + SOIL_TO_MAP.ty };
}

/** The soil tile a Homestead map tile holds. */
export function mapToSoilTile(mx: number, my: number): { tx: number; ty: number } {
  return { tx: mx - SOIL_TO_MAP.tx, ty: my - SOIL_TO_MAP.ty };
}

/** Whether a bed may be broken at this soil tile: the server's whole check. */
export function isHoeableSoilTile(tx: number, ty: number): boolean {
  const { mx, my } = soilToMapTile(tx, ty);
  return isHoeableMapTile(mx, my);
}
