/**
 * GENERATED by scripts/prepare-dealers.py -- do not edit.
 *
 * Every dealer whose art is in `public/table2d5/dealers/`, and the one box
 * they were all normalised onto. Regenerate after adding a plate to the
 * bucket; the box is recomputed from the whole set, so every file is rewritten
 * on each run.
 */

/** Dealer ids, in the order they take the table. */
export const DEALER_IDS = ["finn", "house", "loki"] as const;

/**
 * The shared box, in pixels of the normalised art. Only its ratio is used --
 * the drawn size comes from the camera -- but both numbers are kept so a
 * regeneration that changes the box is visible in the diff.
 */
export const DEALER_BOX = { width: 706, height: 794 } as const;
