/**
 * GENERATED by scripts/prepare-dealer.py -- do not edit.
 *
 * The house dealer's normalised cutout, and the box it was normalised onto.
 * Regenerate after redrawing the plate in `art/dealers/`.
 */

/** The dealer's artwork, served from public/. */
export const DEALER_ART_SRC = "/table2d5/dealer.webp";

/**
 * The normalised box, in pixels of the artwork. Only its ratio is used -- the
 * drawn size comes from the camera -- but both numbers are kept so a
 * regeneration that changes the box is visible in the diff.
 */
export const DEALER_BOX = { width: 596, height: 794 } as const;
