/**
 * GENERATED by scripts/prepare-seat-art.py -- do not edit.
 *
 * Every character with seat art in `public/table2d5/seats/`, the angles
 * available for each (degrees off facing the camera, always the "turns
 * toward screen-left" convention -- see the script's own docstring), and the
 * box its own bucket was normalised onto.
 */

export interface SeatArtCharacter {
  id: string;
  /** Degrees off facing the camera, ascending. Always includes 0. */
  angles: readonly number[];
  /** The shared box this character's angles were normalised onto, in pixels
   *  of the art. Only the ratio matters -- drawn size comes from the camera. */
  box: { width: number; height: number };
}

export const SEAT_ART_CHARACTERS: readonly SeatArtCharacter[] = [
  { id: "character13", angles: [0, 20, 40] as const, box: { width: 334, height: 527 } },
  { id: "character14", angles: [0, 20, 40] as const, box: { width: 328, height: 522 } },
  { id: "character15", angles: [0, 20, 40] as const, box: { width: 324, height: 526 } },
  { id: "character16", angles: [0, 20, 40] as const, box: { width: 326, height: 518 } },
  { id: "character17", angles: [0, 20, 40] as const, box: { width: 334, height: 515 } },
  { id: "character18", angles: [0, 20, 40] as const, box: { width: 326, height: 511 } },
  { id: "character19", angles: [0, 20, 40] as const, box: { width: 354, height: 520 } },
  { id: "character20", angles: [0, 20, 40] as const, box: { width: 334, height: 483 } },
  { id: "character21", angles: [0, 20, 40] as const, box: { width: 324, height: 483 } },
  { id: "character22", angles: [0, 20, 40] as const, box: { width: 328, height: 513 } },
  { id: "character23", angles: [0, 20, 40] as const, box: { width: 322, height: 515 } },
  { id: "character24", angles: [0, 20, 40] as const, box: { width: 360, height: 533 } },
  { id: "character25", angles: [0, 20, 40] as const, box: { width: 372, height: 532 } },
  { id: "character26", angles: [0, 20, 40] as const, box: { width: 328, height: 526 } },
  { id: "character27", angles: [0, 20, 40] as const, box: { width: 298, height: 345 } },
  { id: "character28", angles: [0, 20, 40] as const, box: { width: 328, height: 512 } },
  { id: "character29", angles: [0, 20, 40] as const, box: { width: 384, height: 560 } },
  { id: "character30", angles: [0, 20, 40] as const, box: { width: 374, height: 503 } },
  { id: "character31", angles: [0, 20, 40] as const, box: { width: 380, height: 559 } },
  { id: "character32", angles: [0, 20, 40] as const, box: { width: 454, height: 652 } },
  { id: "character33", angles: [0, 20, 40] as const, box: { width: 434, height: 670 } },
  { id: "character34", angles: [0, 20, 40] as const, box: { width: 440, height: 639 } },
  { id: "character35", angles: [0, 20, 40] as const, box: { width: 352, height: 510 } },
  { id: "character36", angles: [0, 20] as const, box: { width: 350, height: 491 } },
  { id: "character37", angles: [0, 20] as const, box: { width: 316, height: 529 } },
  { id: "character38", angles: [0, 20] as const, box: { width: 318, height: 519 } },
  { id: "character39", angles: [0, 20] as const, box: { width: 322, height: 519 } },
  { id: "character40", angles: [0, 20] as const, box: { width: 330, height: 519 } },
  { id: "character41", angles: [0, 20] as const, box: { width: 320, height: 515 } },
] as const;
