/**
 * GENERATED by scripts/prepare-seat-art.py -- do not edit.
 *
 * Every character with seat art in `public/table2d5/seats/`, the angles
 * available for each (degrees off facing the camera, always the "turns
 * toward screen-left" convention -- see the script's own docstring), and the
 * box its own bucket was normalised onto.
 */

export interface SeatArtCharacter {
  id: string;
  /** Degrees off facing the camera, ascending. Always includes 0. */
  angles: readonly number[];
  /** The shared box this character's angles were normalised onto, in pixels
   *  of the art. Only the ratio matters -- drawn size comes from the camera. */
  box: { width: number; height: number };
}

export const SEAT_ART_CHARACTERS: readonly SeatArtCharacter[] = [
  { id: "character1", angles: [0, 20, 40] as const, box: { width: 892, height: 1047 } },
  { id: "character10", angles: [0, 20, 40] as const, box: { width: 606, height: 501 } },
  { id: "character11", angles: [0, 20, 40] as const, box: { width: 676, height: 508 } },
  { id: "character12", angles: [0, 20, 40] as const, box: { width: 886, height: 1149 } },
  { id: "character13", angles: [0, 20, 40] as const, box: { width: 336, height: 527 } },
  { id: "character14", angles: [0, 20, 40] as const, box: { width: 326, height: 522 } },
  { id: "character15", angles: [0, 20, 40] as const, box: { width: 324, height: 526 } },
  { id: "character16", angles: [0, 20, 40] as const, box: { width: 328, height: 518 } },
  { id: "character17", angles: [0, 20, 40] as const, box: { width: 336, height: 515 } },
  { id: "character18", angles: [0, 20, 40] as const, box: { width: 324, height: 511 } },
  { id: "character19", angles: [0, 20, 40] as const, box: { width: 352, height: 520 } },
  { id: "character2", angles: [0, 20, 40] as const, box: { width: 942, height: 1099 } },
  { id: "character20", angles: [0, 20, 40] as const, box: { width: 336, height: 483 } },
  { id: "character21", angles: [0, 20, 40] as const, box: { width: 326, height: 483 } },
  { id: "character3", angles: [0, 20, 40] as const, box: { width: 794, height: 1120 } },
  { id: "character4", angles: [0, 20, 40] as const, box: { width: 760, height: 1172 } },
  { id: "character5", angles: [0, 20, 40] as const, box: { width: 866, height: 1086 } },
  { id: "character6", angles: [0, 20, 40] as const, box: { width: 530, height: 521 } },
  { id: "character7", angles: [0, 20, 40] as const, box: { width: 622, height: 520 } },
  { id: "character8", angles: [0, 20, 40] as const, box: { width: 646, height: 524 } },
  { id: "character9", angles: [0, 20, 40] as const, box: { width: 580, height: 512 } },
] as const;
