/**
 * GENERATED by scripts/prepare-seat-art.py -- do not edit.
 *
 * Every character with seat art in `public/table2d5/seats/`, the angles
 * available for each (degrees off facing the camera, always the "turns
 * toward screen-left" convention -- see the script's own docstring), and the
 * box its own bucket was normalised onto.
 */

export interface SeatArtCharacter {
  id: string;
  /** Degrees off facing the camera, ascending. Always includes 0. */
  angles: readonly number[];
  /** The shared box this character's angles were normalised onto, in pixels
   *  of the art. Only the ratio matters -- drawn size comes from the camera. */
  box: { width: number; height: number };
}

export const SEAT_ART_CHARACTERS: readonly SeatArtCharacter[] = [
  { id: "character1", angles: [0, 20, 40] as const, box: { width: 898, height: 1075 } },
] as const;
