import "server-only";

/**
 * The questions Trivia Showdown actually asks, and the answers to them.
 *
 * `server-only`, for exactly the reason lib/arcade/puzzles/word-stack-answers.ts
 * is: a browser holding this file hasn't cheated one question, it's cheated
 * every match it will ever play, and this one settles real Gold. The snapshot
 * that reaches a client carries a prompt and four choices with no answerIndex,
 * which is worth nothing if the client also has the table that maps the one
 * to the other.
 *
 * That's a constraint on the import graph, not just on this file. Nothing
 * under components/ may value-import lib/pvp/trivia.ts either, since it
 * imports this; boards take their types from it with `import type`, which the
 * compiler erases. A stray value import fails the build loudly, which is the
 * behaviour we want: silence is what makes a leak expensive.
 *
 * What belongs here is facts that do not rot. No current office-holders, no
 * "largest/tallest/fastest ever", no records, nothing whose truth has a date
 * attached: a question bank is written once and read for years, and a stale
 * answer marked correct is worse than a missing question, because the player
 * who knew better is the one it punishes.
 *
 * Choices are presented in the order they are written (no per-match
 * permutation), so a bank that habitually put the answer first would teach a
 * player to tap the first button and win. trivia.test.ts asserts every
 * position carries a real share of the bank, since "vary it" is the kind of
 * discipline that decays the moment someone appends ten questions in a hurry.
 */

export interface TriviaQuestion {
  /** Stable. A live match stores ids, so renaming one orphans a match in progress. */
  id: string;
  category: string;
  prompt: string;
  /** Exactly four, presented in this order. */
  choices: readonly [string, string, string, string];
  /** Index into `choices`, 0-3. */
  answerIndex: number;
}

export const TRIVIA_QUESTIONS: readonly TriviaQuestion[] = [
  /* ------------------------------------------------ general knowledge */
  {
    id: "gk-1",
    category: "General knowledge",
    prompt: "How many continents are there on Earth?",
    choices: ["Five", "Six", "Seven", "Eight"],
    answerIndex: 2,
  },
  {
    id: "gk-2",
    category: "General knowledge",
    prompt: "How many sides does a hexagon have?",
    choices: ["Three", "Four", "Five", "Six"],
    answerIndex: 3,
  },
  {
    id: "gk-3",
    category: "General knowledge",
    prompt: "Which of these is the largest animal alive today?",
    choices: ["African elephant", "Blue whale", "Giraffe", "Great white shark"],
    answerIndex: 1,
  },
  {
    id: "gk-4",
    category: "General knowledge",
    prompt: "How many degrees are there in a right angle?",
    choices: ["45", "60", "90", "180"],
    answerIndex: 2,
  },
  {
    id: "gk-5",
    category: "General knowledge",
    prompt: "Which Roman numeral stands for 50?",
    choices: ["X", "L", "C", "D"],
    answerIndex: 1,
  },
  {
    id: "gk-6",
    category: "General knowledge",
    prompt: "How many minutes are there in a full day?",
    choices: ["720", "960", "1,440", "2,400"],
    answerIndex: 2,
  },
  {
    id: "gk-7",
    category: "General knowledge",
    prompt: "Mixing blue and yellow paint gives you which colour?",
    choices: ["Purple", "Brown", "Orange", "Green"],
    answerIndex: 3,
  },
  {
    id: "gk-8",
    category: "General knowledge",
    prompt: "What is the currency of Japan?",
    choices: ["Won", "Yuan", "Yen", "Baht"],
    answerIndex: 2,
  },
  {
    id: "gk-9",
    category: "General knowledge",
    prompt: "How many cards are in a standard deck with the jokers removed?",
    choices: ["44", "48", "50", "52"],
    answerIndex: 3,
  },
  {
    id: "gk-10",
    category: "General knowledge",
    prompt: "Which is the tallest living land animal?",
    choices: ["Giraffe", "African elephant", "Ostrich", "Camel"],
    answerIndex: 0,
  },
  {
    id: "gk-11",
    category: "General knowledge",
    prompt: "How many squares are there on a chessboard?",
    choices: ["36", "49", "64", "81"],
    answerIndex: 2,
  },
  {
    id: "gk-12",
    category: "General knowledge",
    prompt: "What does the abbreviation \"www\" stand for?",
    choices: ["Wireless Web World", "World Wide Web", "Web World Wide", "Wide World Web"],
    answerIndex: 1,
  },
  {
    id: "gk-13",
    category: "General knowledge",
    prompt: "Which is the largest organ of the human body?",
    choices: ["Liver", "Brain", "Skin", "Lungs"],
    answerIndex: 2,
  },
  {
    id: "gk-14",
    category: "General knowledge",
    prompt: "What is a baby kangaroo called?",
    choices: ["Cub", "Kit", "Calf", "Joey"],
    answerIndex: 3,
  },
  {
    id: "gk-15",
    category: "General knowledge",
    prompt: "Which is the only mammal capable of true powered flight?",
    choices: ["Bat", "Flying squirrel", "Colugo", "Sugar glider"],
    answerIndex: 0,
  },
  {
    id: "gk-16",
    category: "General knowledge",
    prompt: "How many zeros are in the numeral 1,000,000?",
    choices: ["Five", "Six", "Seven", "Nine"],
    answerIndex: 1,
  },
  {
    id: "gk-17",
    category: "General knowledge",
    prompt: "How many pieces does each player start a game of chess with?",
    choices: ["Eight", "Twelve", "Sixteen", "Twenty"],
    answerIndex: 2,
  },
  {
    id: "gk-18",
    category: "General knowledge",
    prompt: "What is the currency of the United Kingdom?",
    choices: ["Euro", "Pound sterling", "Krona", "Franc"],
    answerIndex: 1,
  },
  {
    id: "gk-19",
    category: "General knowledge",
    prompt: "At what temperature does water freeze, in degrees Celsius?",
    choices: ["-100", "-32", "-10", "0"],
    answerIndex: 3,
  },
  {
    id: "gk-20",
    category: "General knowledge",
    prompt: "Which of these shapes has no straight sides at all?",
    choices: ["Triangle", "Square", "Circle", "Pentagon"],
    answerIndex: 2,
  },
  {
    id: "gk-21",
    category: "General knowledge",
    prompt: "How many colours are traditionally named in a rainbow?",
    choices: ["Five", "Six", "Seven", "Eight"],
    answerIndex: 2,
  },
  {
    id: "gk-22",
    category: "General knowledge",
    prompt: "How many hours are there in a week?",
    choices: ["144", "168", "180", "196"],
    answerIndex: 1,
  },

  /* ------------------------------------------------------- geography */
  {
    id: "geo-1",
    category: "Geography",
    prompt: "What is the capital of Australia?",
    choices: ["Sydney", "Melbourne", "Canberra", "Perth"],
    answerIndex: 2,
  },
  {
    id: "geo-2",
    category: "Geography",
    prompt: "What is the capital of Canada?",
    choices: ["Ottawa", "Toronto", "Vancouver", "Montreal"],
    answerIndex: 0,
  },
  {
    id: "geo-3",
    category: "Geography",
    prompt: "Which river runs through the Amazon rainforest?",
    choices: ["Orinoco", "Paraná", "Amazon", "Magdalena"],
    answerIndex: 2,
  },
  {
    id: "geo-4",
    category: "Geography",
    prompt: "On which continent is the Sahara Desert?",
    choices: ["Asia", "Africa", "Australia", "South America"],
    answerIndex: 1,
  },
  {
    id: "geo-5",
    category: "Geography",
    prompt: "Which ocean lies between Africa and Australia?",
    choices: ["Atlantic", "Pacific", "Arctic", "Indian"],
    answerIndex: 3,
  },
  {
    id: "geo-6",
    category: "Geography",
    prompt: "In which country would you find Mount Fuji?",
    choices: ["Japan", "China", "South Korea", "Nepal"],
    answerIndex: 0,
  },
  {
    id: "geo-7",
    category: "Geography",
    prompt: "What is the capital of Brazil?",
    choices: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
    answerIndex: 2,
  },
  {
    id: "geo-8",
    category: "Geography",
    prompt: "Which sea separates southern Europe from northern Africa?",
    choices: ["Baltic Sea", "Mediterranean Sea", "Caspian Sea", "Black Sea"],
    answerIndex: 1,
  },
  {
    id: "geo-9",
    category: "Geography",
    prompt: "Which US state is nicknamed the Sunshine State?",
    choices: ["California", "Arizona", "Hawaii", "Florida"],
    answerIndex: 3,
  },
  {
    id: "geo-10",
    category: "Geography",
    prompt: "Which country's flag is a plain red circle on a white field?",
    choices: ["South Korea", "Japan", "Bangladesh", "Nepal"],
    answerIndex: 1,
  },
  {
    id: "geo-11",
    category: "Geography",
    prompt: "Which mountain range forms the border between Spain and France?",
    choices: ["The Alps", "The Apennines", "The Pyrenees", "The Carpathians"],
    answerIndex: 2,
  },
  {
    id: "geo-12",
    category: "Geography",
    prompt: "Which country was historically known as Abyssinia?",
    choices: ["Sudan", "Somalia", "Eritrea", "Ethiopia"],
    answerIndex: 3,
  },
  {
    id: "geo-13",
    category: "Geography",
    prompt: "The Strait of Gibraltar separates Spain from which country?",
    choices: ["Morocco", "Algeria", "Tunisia", "Libya"],
    answerIndex: 0,
  },
  {
    id: "geo-14",
    category: "Geography",
    prompt: "In which city would you find the Colosseum?",
    choices: ["Athens", "Naples", "Rome", "Florence"],
    answerIndex: 2,
  },
  {
    id: "geo-15",
    category: "Geography",
    prompt: "What is the capital of New Zealand?",
    choices: ["Auckland", "Wellington", "Christchurch", "Dunedin"],
    answerIndex: 1,
  },
  {
    id: "geo-16",
    category: "Geography",
    prompt: "Which country completely surrounds Lesotho?",
    choices: ["Namibia", "Botswana", "Zimbabwe", "South Africa"],
    answerIndex: 3,
  },
  {
    id: "geo-17",
    category: "Geography",
    prompt: "Which river flows through London?",
    choices: ["The Thames", "The Severn", "The Mersey", "The Tyne"],
    answerIndex: 0,
  },
  {
    id: "geo-18",
    category: "Geography",
    prompt: "Greenland is an autonomous territory of which country?",
    choices: ["Norway", "Iceland", "Denmark", "Canada"],
    answerIndex: 2,
  },
  {
    id: "geo-19",
    category: "Geography",
    prompt: "What is the capital of Norway?",
    choices: ["Bergen", "Oslo", "Stavanger", "Trondheim"],
    answerIndex: 1,
  },
  {
    id: "geo-20",
    category: "Geography",
    prompt: "Which country covers the largest land area in the world?",
    choices: ["Canada", "China", "Russia", "United States"],
    answerIndex: 2,
  },
  {
    id: "geo-21",
    category: "Geography",
    prompt: "The Great Barrier Reef lies off the coast of which country?",
    choices: ["Australia", "Brazil", "Mexico", "Indonesia"],
    answerIndex: 0,
  },
  {
    id: "geo-22",
    category: "Geography",
    prompt: "Which desert covers much of Mongolia and northern China?",
    choices: ["Kalahari", "Atacama", "Thar", "Gobi"],
    answerIndex: 3,
  },
  {
    id: "geo-23",
    category: "Geography",
    prompt: "Which two countries share the longest land border in the world?",
    choices: [
      "Russia and China",
      "Canada and the United States",
      "Argentina and Chile",
      "India and Bangladesh",
    ],
    answerIndex: 1,
  },
  {
    id: "geo-24",
    category: "Geography",
    prompt: "Which canal connects the Mediterranean Sea to the Red Sea?",
    choices: ["Panama Canal", "Suez Canal", "Kiel Canal", "Corinth Canal"],
    answerIndex: 1,
  },

  /* --------------------------------------------------------- science */
  {
    id: "sci-1",
    category: "Science",
    prompt: "What is the chemical symbol for gold?",
    choices: ["Go", "Gd", "Au", "Ag"],
    answerIndex: 2,
  },
  {
    id: "sci-2",
    category: "Science",
    prompt: "How many bones are there in the adult human body?",
    choices: ["166", "186", "196", "206"],
    answerIndex: 3,
  },
  {
    id: "sci-3",
    category: "Science",
    prompt: "Which gas do plants take in during photosynthesis?",
    choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
    answerIndex: 2,
  },
  {
    id: "sci-4",
    category: "Science",
    prompt: "Which planet is known as the Red Planet?",
    choices: ["Mars", "Venus", "Jupiter", "Mercury"],
    answerIndex: 0,
  },
  {
    id: "sci-5",
    category: "Science",
    prompt: "Which blood cells are the body's main defence against infection?",
    choices: ["Red blood cells", "White blood cells", "Platelets", "Stem cells"],
    answerIndex: 1,
  },
  {
    id: "sci-6",
    category: "Science",
    prompt: "Roughly how fast does light travel in a vacuum?",
    choices: [
      "3,000 kilometres per second",
      "30,000 kilometres per second",
      "300,000 kilometres per second",
      "3,000,000 kilometres per second",
    ],
    answerIndex: 2,
  },
  {
    id: "sci-7",
    category: "Science",
    prompt: "What is the atomic number of carbon?",
    choices: ["2", "4", "5", "6"],
    answerIndex: 3,
  },
  {
    id: "sci-8",
    category: "Science",
    prompt: "Which planet has the storm known as the Great Red Spot?",
    choices: ["Saturn", "Neptune", "Jupiter", "Uranus"],
    answerIndex: 2,
  },
  {
    id: "sci-9",
    category: "Science",
    prompt: "Which is the hardest naturally occurring mineral?",
    choices: ["Quartz", "Corundum", "Topaz", "Diamond"],
    answerIndex: 3,
  },
  {
    id: "sci-10",
    category: "Science",
    prompt: "What does DNA stand for?",
    choices: [
      "Deoxyribonucleic acid",
      "Dinucleic acid",
      "Diribonucleic acid",
      "Deoxyribose nucleotide array",
    ],
    answerIndex: 0,
  },
  {
    id: "sci-11",
    category: "Science",
    prompt: "Which part of a cell is usually described as its powerhouse?",
    choices: ["Nucleus", "Ribosome", "Mitochondrion", "Golgi body"],
    answerIndex: 2,
  },
  {
    id: "sci-12",
    category: "Science",
    prompt: "Which vitamin does the body make when skin is exposed to sunlight?",
    choices: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"],
    answerIndex: 2,
  },
  {
    id: "sci-13",
    category: "Science",
    prompt: "What is the chemical symbol for sodium?",
    choices: ["So", "Na", "Sd", "Sn"],
    answerIndex: 1,
  },
  {
    id: "sci-14",
    category: "Science",
    prompt: "How many chambers does the human heart have?",
    choices: ["Two", "Three", "Four", "Six"],
    answerIndex: 2,
  },
  {
    id: "sci-15",
    category: "Science",
    prompt: "Which is the largest planet in the solar system?",
    choices: ["Saturn", "Jupiter", "Neptune", "Earth"],
    answerIndex: 1,
  },
  {
    id: "sci-16",
    category: "Science",
    prompt: "Which scale is used to measure how acidic or alkaline something is?",
    choices: ["The Richter scale", "The pH scale", "The Kelvin scale", "The Mohs scale"],
    answerIndex: 1,
  },
  {
    id: "sci-17",
    category: "Science",
    prompt: "Who published the general theory of relativity?",
    choices: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"],
    answerIndex: 2,
  },
  {
    id: "sci-18",
    category: "Science",
    prompt: "At what temperature does water freeze, in degrees Fahrenheit?",
    choices: ["0", "32", "48", "100"],
    answerIndex: 1,
  },
  {
    id: "sci-19",
    category: "Science",
    prompt: "What is the study of fossils called?",
    choices: ["Archaeology", "Geology", "Paleontology", "Anthropology"],
    answerIndex: 2,
  },
  {
    id: "sci-20",
    category: "Science",
    prompt: "Which gas makes up the greatest share of Earth's atmosphere?",
    choices: ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"],
    answerIndex: 0,
  },
  {
    id: "sci-21",
    category: "Science",
    prompt: "How many planets orbit the Sun?",
    choices: ["Seven", "Eight", "Nine", "Ten"],
    answerIndex: 1,
  },
  {
    id: "sci-22",
    category: "Science",
    prompt: "What is the chemical symbol for iron?",
    choices: ["Ir", "In", "Fe", "Fr"],
    answerIndex: 2,
  },
  {
    id: "sci-23",
    category: "Science",
    prompt: "How many legs does an adult insect have?",
    choices: ["Two", "Three", "Four", "Six"],
    answerIndex: 3,
  },
  {
    id: "sci-24",
    category: "Science",
    prompt: "How many legs does a spider have?",
    choices: ["Six", "Eight", "Ten", "Twelve"],
    answerIndex: 1,
  },
  {
    id: "sci-25",
    category: "Science",
    prompt: "Which structure in a plant cell carries out photosynthesis?",
    choices: ["Vacuole", "Chloroplast", "Cell wall", "Nucleus"],
    answerIndex: 1,
  },
  {
    id: "sci-26",
    category: "Science",
    prompt: "What is absolute zero, in degrees Celsius?",
    choices: ["-100", "-173.15", "-273.15", "-373.15"],
    answerIndex: 2,
  },
  {
    id: "sci-27",
    category: "Science",
    prompt: "Which force keeps the planets in orbit around the Sun?",
    choices: ["Magnetism", "Gravity", "Friction", "The strong nuclear force"],
    answerIndex: 1,
  },
  {
    id: "sci-28",
    category: "Science",
    prompt: "Which gas is used to fill party balloons so that they float?",
    choices: ["Hydrogen", "Neon", "Helium", "Argon"],
    answerIndex: 2,
  },
  {
    id: "sci-29",
    category: "Science",
    prompt: "At sea level, water boils at what temperature in degrees Celsius?",
    choices: ["90", "95", "100", "120"],
    answerIndex: 2,
  },
  {
    id: "sci-30",
    category: "Science",
    prompt: "Which of these is a noble gas?",
    choices: ["Nitrogen", "Chlorine", "Oxygen", "Neon"],
    answerIndex: 3,
  },

  /* --------------------------------------------------------- history */
  {
    id: "his-1",
    category: "History",
    prompt: "In which year did the Second World War end?",
    choices: ["1943", "1944", "1945", "1946"],
    answerIndex: 2,
  },
  {
    id: "his-2",
    category: "History",
    prompt: "Who was the first president of the United States?",
    choices: ["Thomas Jefferson", "John Adams", "Benjamin Franklin", "George Washington"],
    answerIndex: 3,
  },
  {
    id: "his-3",
    category: "History",
    prompt: "Which civilisation built Machu Picchu?",
    choices: ["The Maya", "The Aztecs", "The Inca", "The Olmec"],
    answerIndex: 2,
  },
  {
    id: "his-4",
    category: "History",
    prompt: "In which year did the Berlin Wall fall?",
    choices: ["1987", "1989", "1991", "1993"],
    answerIndex: 1,
  },
  {
    id: "his-5",
    category: "History",
    prompt: "Who was the first person to walk on the Moon?",
    choices: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins", "Neil Armstrong"],
    answerIndex: 3,
  },
  {
    id: "his-6",
    category: "History",
    prompt: "Which ocean liner sank on her maiden voyage in 1912?",
    choices: ["Lusitania", "Titanic", "Britannic", "Mauretania"],
    answerIndex: 1,
  },
  {
    id: "his-7",
    category: "History",
    prompt: "What was the writing system of ancient Egypt called?",
    choices: ["Cuneiform", "Hieroglyphs", "Runes", "Linear B"],
    answerIndex: 1,
  },
  {
    id: "his-8",
    category: "History",
    prompt: "Who was the principal author of the American Declaration of Independence?",
    choices: ["Thomas Jefferson", "James Madison", "Alexander Hamilton", "John Jay"],
    answerIndex: 0,
  },
  {
    id: "his-9",
    category: "History",
    prompt: "In which year did the French Revolution begin?",
    choices: ["1776", "1789", "1799", "1812"],
    answerIndex: 1,
  },
  {
    id: "his-10",
    category: "History",
    prompt: "In which year did the American Civil War begin?",
    choices: ["1849", "1855", "1861", "1865"],
    answerIndex: 2,
  },
  {
    id: "his-11",
    category: "History",
    prompt: "Who was British prime minister for most of the Second World War?",
    choices: ["Neville Chamberlain", "Clement Attlee", "Winston Churchill", "Anthony Eden"],
    answerIndex: 2,
  },
  {
    id: "his-12",
    category: "History",
    prompt: "The Parthenon was built by which ancient civilisation?",
    choices: ["The Romans", "The Greeks", "The Persians", "The Phoenicians"],
    answerIndex: 1,
  },
  {
    id: "his-13",
    category: "History",
    prompt: "In which year was Magna Carta sealed?",
    choices: ["1066", "1086", "1189", "1215"],
    answerIndex: 3,
  },
  {
    id: "his-14",
    category: "History",
    prompt: "Who discovered penicillin?",
    choices: ["Louis Pasteur", "Robert Koch", "Alexander Fleming", "Edward Jenner"],
    answerIndex: 2,
  },
  {
    id: "his-15",
    category: "History",
    prompt: "Which country gave the Statue of Liberty to the United States?",
    choices: ["Britain", "Spain", "Italy", "France"],
    answerIndex: 3,
  },
  {
    id: "his-16",
    category: "History",
    prompt: "The Cold War was chiefly a standoff between the United States and which country?",
    choices: ["China", "The Soviet Union", "Germany", "Cuba"],
    answerIndex: 1,
  },
  {
    id: "his-17",
    category: "History",
    prompt: "Who was the first emperor of Rome?",
    choices: ["Julius Caesar", "Nero", "Augustus", "Trajan"],
    answerIndex: 2,
  },
  {
    id: "his-18",
    category: "History",
    prompt: "In which year did Apollo 11 land on the Moon?",
    choices: ["1961", "1965", "1969", "1972"],
    answerIndex: 2,
  },
  {
    id: "his-19",
    category: "History",
    prompt: "Which Roman wall was built across northern England?",
    choices: ["Offa's Dyke", "Hadrian's Wall", "The Antonine Wall", "The Great Wall"],
    answerIndex: 1,
  },
  {
    id: "his-20",
    category: "History",
    prompt: "Who painted the ceiling of the Sistine Chapel?",
    choices: ["Raphael", "Donatello", "Michelangelo", "Botticelli"],
    answerIndex: 2,
  },
  {
    id: "his-21",
    category: "History",
    prompt: "The Battle of Hastings was fought in which year?",
    choices: ["911", "1066", "1215", "1348"],
    answerIndex: 1,
  },
  {
    id: "his-22",
    category: "History",
    prompt: "Which ancient wonder stood in the harbour of Alexandria?",
    choices: [
      "The Hanging Gardens",
      "The Colossus",
      "The Lighthouse",
      "The Mausoleum",
    ],
    answerIndex: 2,
  },

  /* ----------------------------------------------------- film and TV */
  {
    id: "flm-1",
    category: "Film & TV",
    prompt: "\"May the Force be with you\" comes from which film series?",
    choices: ["Star Trek", "Star Wars", "Dune", "Battlestar Galactica"],
    answerIndex: 1,
  },
  {
    id: "flm-2",
    category: "Film & TV",
    prompt: "Who directed the 1975 film Jaws?",
    choices: ["George Lucas", "Ridley Scott", "Steven Spielberg", "Martin Scorsese"],
    answerIndex: 2,
  },
  {
    id: "flm-3",
    category: "Film & TV",
    prompt: "In The Matrix, which colour pill does Neo swallow?",
    choices: ["Blue", "Green", "White", "Red"],
    answerIndex: 3,
  },
  {
    id: "flm-4",
    category: "Film & TV",
    prompt: "Which animated film features a lion cub named Simba?",
    choices: ["Madagascar", "The Jungle Book", "The Lion King", "Zootopia"],
    answerIndex: 2,
  },
  {
    id: "flm-5",
    category: "Film & TV",
    prompt: "What is the name of the wizarding school in the Harry Potter films?",
    choices: ["Hogwarts", "Beauxbatons", "Durmstrang", "Ilvermorny"],
    answerIndex: 0,
  },
  {
    id: "flm-6",
    category: "Film & TV",
    prompt: "Frodo Baggins is a character in which film series?",
    choices: ["The Chronicles of Narnia", "The Hobbit", "The Lord of the Rings", "Willow"],
    answerIndex: 2,
  },
  {
    id: "flm-7",
    category: "Film & TV",
    prompt: "Who played Jack Dawson in the 1997 film Titanic?",
    choices: ["Brad Pitt", "Leonardo DiCaprio", "Matt Damon", "Johnny Depp"],
    answerIndex: 1,
  },
  {
    id: "flm-8",
    category: "Film & TV",
    prompt: "\"Life is like a box of chocolates\" is a line from which film?",
    choices: ["Rain Man", "Forrest Gump", "Big", "Cast Away"],
    answerIndex: 1,
  },
  {
    id: "flm-9",
    category: "Film & TV",
    prompt: "Game of Thrones is largely set on which continent?",
    choices: ["Essos", "Sothoryos", "Westeros", "Ulthos"],
    answerIndex: 2,
  },
  {
    id: "flm-10",
    category: "Film & TV",
    prompt: "Which studio made the first Toy Story film?",
    choices: ["DreamWorks", "Pixar", "Illumination", "Blue Sky"],
    answerIndex: 1,
  },
  {
    id: "flm-11",
    category: "Film & TV",
    prompt: "In Back to the Future, what kind of car is the time machine?",
    choices: ["Ford Mustang", "Chevrolet Corvette", "DeLorean", "Pontiac Firebird"],
    answerIndex: 2,
  },
  {
    id: "flm-12",
    category: "Film & TV",
    prompt: "Who directed Pulp Fiction?",
    choices: ["Quentin Tarantino", "Robert Rodriguez", "Guy Ritchie", "Coen brothers"],
    answerIndex: 0,
  },
  {
    id: "flm-13",
    category: "Film & TV",
    prompt: "Which sitcom's characters meet at a coffee house called Central Perk?",
    choices: ["Seinfeld", "Friends", "Cheers", "How I Met Your Mother"],
    answerIndex: 1,
  },
  {
    id: "flm-14",
    category: "Film & TV",
    prompt: "What is the name of Luke Skywalker's home planet?",
    choices: ["Hoth", "Endor", "Naboo", "Tatooine"],
    answerIndex: 3,
  },
  {
    id: "flm-15",
    category: "Film & TV",
    prompt: "Hannibal Lecter is the antagonist of which 1991 film?",
    choices: ["Se7en", "The Silence of the Lambs", "Cape Fear", "Misery"],
    answerIndex: 1,
  },
  {
    id: "flm-16",
    category: "Film & TV",
    prompt: "Who voices Woody in the Toy Story films?",
    choices: ["Tim Allen", "Tom Hanks", "Billy Crystal", "John Ratzenberger"],
    answerIndex: 1,
  },
  {
    id: "flm-17",
    category: "Film & TV",
    prompt: "Who directed Inception?",
    choices: ["Denis Villeneuve", "David Fincher", "Christopher Nolan", "Alfonso Cuarón"],
    answerIndex: 2,
  },
  {
    id: "flm-18",
    category: "Film & TV",
    prompt: "Walter White is the central character of which television series?",
    choices: ["The Wire", "Breaking Bad", "Better Call Saul", "Ozark"],
    answerIndex: 1,
  },
  {
    id: "flm-19",
    category: "Film & TV",
    prompt: "In the 1939 film The Wizard of Oz, what colour are Dorothy's slippers?",
    choices: ["Silver", "Gold", "Ruby red", "Emerald green"],
    answerIndex: 2,
  },
  {
    id: "flm-20",
    category: "Film & TV",
    prompt: "\"I'll be back\" is a catchphrase from which film?",
    choices: ["Predator", "The Terminator", "Commando", "Total Recall"],
    answerIndex: 1,
  },
  {
    id: "flm-21",
    category: "Film & TV",
    prompt: "Which film is set in a snowbound hotel called the Overlook?",
    choices: ["Psycho", "The Shining", "Misery", "The Others"],
    answerIndex: 1,
  },
  {
    id: "flm-22",
    category: "Film & TV",
    prompt: "In which sport does the film character Rocky Balboa compete?",
    choices: ["Wrestling", "Boxing", "Mixed martial arts", "Athletics"],
    answerIndex: 1,
  },
  {
    id: "flm-23",
    category: "Film & TV",
    prompt: "In which town do The Simpsons live?",
    choices: ["Shelbyville", "Springfield", "Quahog", "Langley Falls"],
    answerIndex: 1,
  },
  {
    id: "flm-24",
    category: "Film & TV",
    prompt: "Ariel is the heroine of which animated Disney film?",
    choices: ["Moana", "Pocahontas", "The Little Mermaid", "Frozen"],
    answerIndex: 2,
  },
  {
    id: "flm-25",
    category: "Film & TV",
    prompt: "Who directed the 1972 film The Godfather?",
    choices: ["Sidney Lumet", "Francis Ford Coppola", "Roman Polanski", "William Friedkin"],
    answerIndex: 1,
  },
  {
    id: "flm-26",
    category: "Film & TV",
    prompt: "Which film introduced the character Indiana Jones?",
    choices: [
      "Raiders of the Lost Ark",
      "The Temple of Doom",
      "The Last Crusade",
      "The Crystal Skull",
    ],
    answerIndex: 0,
  },

  /* ----------------------------------------------------------- music */
  {
    id: "mus-1",
    category: "Music",
    prompt: "How many strings does a standard guitar have?",
    choices: ["Four", "Five", "Six", "Seven"],
    answerIndex: 2,
  },
  {
    id: "mus-2",
    category: "Music",
    prompt: "Which band recorded Bohemian Rhapsody?",
    choices: ["Led Zeppelin", "The Who", "Pink Floyd", "Queen"],
    answerIndex: 3,
  },
  {
    id: "mus-3",
    category: "Music",
    prompt: "Which instrument has 88 keys?",
    choices: ["Organ", "Harpsichord", "Piano", "Accordion"],
    answerIndex: 2,
  },
  {
    id: "mus-4",
    category: "Music",
    prompt: "Which singer is known as the King of Pop?",
    choices: ["Prince", "Michael Jackson", "Elvis Presley", "Stevie Wonder"],
    answerIndex: 1,
  },
  {
    id: "mus-5",
    category: "Music",
    prompt: "Ode to Joy appears in the ninth symphony of which composer?",
    choices: ["Mozart", "Bach", "Beethoven", "Brahms"],
    answerIndex: 2,
  },
  {
    id: "mus-6",
    category: "Music",
    prompt: "In musical notation, what does \"forte\" instruct a player to do?",
    choices: ["Play softly", "Play loudly", "Play faster", "Play slower"],
    answerIndex: 1,
  },
  {
    id: "mus-7",
    category: "Music",
    prompt: "Reggae music originated in which country?",
    choices: ["Trinidad and Tobago", "Cuba", "Jamaica", "Barbados"],
    answerIndex: 2,
  },
  {
    id: "mus-8",
    category: "Music",
    prompt: "Which band released the album Abbey Road?",
    choices: ["The Rolling Stones", "The Beatles", "The Kinks", "The Beach Boys"],
    answerIndex: 1,
  },
  {
    id: "mus-9",
    category: "Music",
    prompt: "How many lines are there in a standard musical staff?",
    choices: ["Four", "Five", "Six", "Seven"],
    answerIndex: 1,
  },
  {
    id: "mus-10",
    category: "Music",
    prompt: "Yo-Yo Ma is celebrated for playing which instrument?",
    choices: ["Violin", "Cello", "Piano", "Flute"],
    answerIndex: 1,
  },
  {
    id: "mus-11",
    category: "Music",
    prompt: "Elvis Presley was nicknamed the King of what?",
    choices: ["Country", "Rock and roll", "Soul", "Blues"],
    answerIndex: 1,
  },
  {
    id: "mus-12",
    category: "Music",
    prompt: "Which is the largest brass instrument in an orchestra?",
    choices: ["Trombone", "French horn", "Trumpet", "Tuba"],
    answerIndex: 3,
  },
  {
    id: "mus-13",
    category: "Music",
    prompt: "What does \"DJ\" stand for?",
    choices: ["Disc jockey", "Dance jockey", "Digital jockey", "Double jack"],
    answerIndex: 0,
  },
  {
    id: "mus-14",
    category: "Music",
    prompt: "Who composed the opera The Magic Flute?",
    choices: ["Verdi", "Wagner", "Mozart", "Puccini"],
    answerIndex: 2,
  },
  {
    id: "mus-15",
    category: "Music",
    prompt: "What does it mean to sing \"a cappella\"?",
    choices: [
      "Singing in a round",
      "Singing without instruments",
      "Singing in falsetto",
      "Singing in unison",
    ],
    answerIndex: 1,
  },
  {
    id: "mus-16",
    category: "Music",
    prompt: "In which year did the Beatles officially break up?",
    choices: ["1966", "1968", "1970", "1973"],
    answerIndex: 2,
  },
  {
    id: "mus-17",
    category: "Music",
    prompt: "Bob Marley is most associated with which genre?",
    choices: ["Ska", "Reggae", "Calypso", "Soca"],
    answerIndex: 1,
  },
  {
    id: "mus-18",
    category: "Music",
    prompt: "Which is the highest of the standard female singing voices?",
    choices: ["Alto", "Mezzo-soprano", "Soprano", "Contralto"],
    answerIndex: 2,
  },
  {
    id: "mus-19",
    category: "Music",
    prompt: "How many strings does a standard violin have?",
    choices: ["Four", "Five", "Six", "Eight"],
    answerIndex: 0,
  },
  {
    id: "mus-20",
    category: "Music",
    prompt: "What does a crescendo instruct a musician to do?",
    choices: [
      "Gradually get louder",
      "Gradually get quieter",
      "Stop abruptly",
      "Repeat the passage",
    ],
    answerIndex: 0,
  },
  {
    id: "mus-21",
    category: "Music",
    prompt: "Which of these instruments belongs to the woodwind family?",
    choices: ["Viola", "Clarinet", "Cornet", "Timpani"],
    answerIndex: 1,
  },

  /* ----------------------------------------------------------- sport */
  {
    id: "spt-1",
    category: "Sport",
    prompt: "How many players does each side field in association football?",
    choices: ["Nine", "Ten", "Eleven", "Twelve"],
    answerIndex: 2,
  },
  {
    id: "spt-2",
    category: "Sport",
    prompt: "How many holes are played in a full round of golf?",
    choices: ["Nine", "Twelve", "Eighteen", "Twenty-four"],
    answerIndex: 2,
  },
  {
    id: "spt-3",
    category: "Sport",
    prompt: "In tennis, what word is used for a score of zero?",
    choices: ["Nil", "Duck", "Love", "Blank"],
    answerIndex: 2,
  },
  {
    id: "spt-4",
    category: "Sport",
    prompt: "How often are the Summer Olympic Games normally held?",
    choices: ["Every two years", "Every three years", "Every four years", "Every five years"],
    answerIndex: 2,
  },
  {
    id: "spt-5",
    category: "Sport",
    prompt: "Which sport is played with a shuttlecock?",
    choices: ["Squash", "Table tennis", "Pickleball", "Badminton"],
    answerIndex: 3,
  },
  {
    id: "spt-6",
    category: "Sport",
    prompt: "In American football, how many points is a touchdown worth?",
    choices: ["Three", "Five", "Six", "Seven"],
    answerIndex: 2,
  },
  {
    id: "spt-7",
    category: "Sport",
    prompt: "Judo originated in which country?",
    choices: ["China", "Korea", "Japan", "Thailand"],
    answerIndex: 2,
  },
  {
    id: "spt-8",
    category: "Sport",
    prompt: "In basketball, how many points is a successful free throw worth?",
    choices: ["One", "Two", "Three", "Four"],
    answerIndex: 0,
  },
  {
    id: "spt-9",
    category: "Sport",
    prompt: "The Tour de France is a competition in which sport?",
    choices: ["Running", "Cycling", "Motor racing", "Rowing"],
    answerIndex: 1,
  },
  {
    id: "spt-10",
    category: "Sport",
    prompt: "How many players from each team are on a basketball court at once?",
    choices: ["Four", "Five", "Six", "Seven"],
    answerIndex: 1,
  },
  {
    id: "spt-11",
    category: "Sport",
    prompt: "In football, which colour card sends a player off?",
    choices: ["Yellow", "Red", "Blue", "Black"],
    answerIndex: 1,
  },
  {
    id: "spt-12",
    category: "Sport",
    prompt: "How many legal deliveries make up an over in cricket?",
    choices: ["Four", "Five", "Six", "Eight"],
    answerIndex: 2,
  },
  {
    id: "spt-13",
    category: "Sport",
    prompt: "Which sport is played at Wimbledon?",
    choices: ["Cricket", "Tennis", "Croquet", "Polo"],
    answerIndex: 1,
  },
  {
    id: "spt-14",
    category: "Sport",
    prompt: "How long is a marathon?",
    choices: ["21.1 km", "32.2 km", "42.195 km", "50 km"],
    answerIndex: 2,
  },
  {
    id: "spt-15",
    category: "Sport",
    prompt: "In which sport would you perform a slam dunk?",
    choices: ["Volleyball", "Basketball", "Handball", "Netball"],
    answerIndex: 1,
  },
  {
    id: "spt-16",
    category: "Sport",
    prompt: "How many interlocking rings are on the Olympic flag?",
    choices: ["Two", "Three", "Four", "Five"],
    answerIndex: 3,
  },
  {
    id: "spt-17",
    category: "Sport",
    prompt: "What is the highest break possible on a standard snooker table?",
    choices: ["120", "138", "147", "155"],
    answerIndex: 2,
  },
  {
    id: "spt-18",
    category: "Sport",
    prompt: "In baseball, how many strikes make a strikeout?",
    choices: ["Two", "Three", "Four", "Five"],
    answerIndex: 1,
  },
  {
    id: "spt-19",
    category: "Sport",
    prompt: "How many players are on a rugby union team on the field?",
    choices: ["Eleven", "Thirteen", "Fifteen", "Seventeen"],
    answerIndex: 2,
  },
  {
    id: "spt-20",
    category: "Sport",
    prompt: "What is the object hit with a stick in ice hockey called?",
    choices: ["Ball", "Puck", "Disc", "Bird"],
    answerIndex: 1,
  },
  {
    id: "spt-21",
    category: "Sport",
    prompt: "In Formula 1, which flag signals the end of a race?",
    choices: ["Yellow flag", "Red flag", "Chequered flag", "Blue flag"],
    answerIndex: 2,
  },
  {
    id: "spt-22",
    category: "Sport",
    prompt: "In football, a hat-trick means one player scored how many goals?",
    choices: ["Two", "Three", "Four", "Five"],
    answerIndex: 1,
  },
  {
    id: "spt-23",
    category: "Sport",
    prompt: "Sumo wrestling is the traditional sport of which country?",
    choices: ["Mongolia", "China", "Japan", "Korea"],
    answerIndex: 2,
  },

  /* ------------------------------------------------------------ food */
  {
    id: "fud-1",
    category: "Food & drink",
    prompt: "Which spice is the most expensive in the world by weight?",
    choices: ["Vanilla", "Cardamom", "Saffron", "Cinnamon"],
    answerIndex: 2,
  },
  {
    id: "fud-2",
    category: "Food & drink",
    prompt: "Which fruit is the base of guacamole?",
    choices: ["Avocado", "Tomatillo", "Lime", "Mango"],
    answerIndex: 0,
  },
  {
    id: "fud-3",
    category: "Food & drink",
    prompt: "Pizza in its modern form originated in which country?",
    choices: ["Greece", "France", "Spain", "Italy"],
    answerIndex: 3,
  },
  {
    id: "fud-4",
    category: "Food & drink",
    prompt: "Tofu is made from which ingredient?",
    choices: ["Rice", "Wheat", "Soybeans", "Chickpeas"],
    answerIndex: 2,
  },
  {
    id: "fud-5",
    category: "Food & drink",
    prompt: "Sushi is traditionally a dish of which country?",
    choices: ["China", "Japan", "Korea", "Vietnam"],
    answerIndex: 1,
  },
  {
    id: "fud-6",
    category: "Food & drink",
    prompt: "Marzipan is made mainly from sugar and which nut?",
    choices: ["Hazelnut", "Walnut", "Almond", "Pistachio"],
    answerIndex: 2,
  },
  {
    id: "fud-7",
    category: "Food & drink",
    prompt: "Wine is made by fermenting which fruit?",
    choices: ["Apples", "Grapes", "Pears", "Plums"],
    answerIndex: 1,
  },
  {
    id: "fud-8",
    category: "Food & drink",
    prompt: "Which pulse is the main ingredient of hummus?",
    choices: ["Lentils", "Butter beans", "Chickpeas", "Black beans"],
    answerIndex: 2,
  },
  {
    id: "fud-9",
    category: "Food & drink",
    prompt: "Basmati is a variety of what?",
    choices: ["Rice", "Wheat", "Tea", "Lentil"],
    answerIndex: 0,
  },
  {
    id: "fud-10",
    category: "Food & drink",
    prompt: "Which vegetable is notorious for making cooks cry when sliced?",
    choices: ["Leek", "Cabbage", "Onion", "Celery"],
    answerIndex: 2,
  },
  {
    id: "fud-11",
    category: "Food & drink",
    prompt: "Which herb gives classic pesto its colour and flavour?",
    choices: ["Parsley", "Basil", "Coriander", "Mint"],
    answerIndex: 1,
  },
  {
    id: "fud-12",
    category: "Food & drink",
    prompt: "Kombucha is made by fermenting what?",
    choices: ["Milk", "Barley", "Tea", "Cabbage"],
    answerIndex: 2,
  },
  {
    id: "fud-13",
    category: "Food & drink",
    prompt: "Paella is a traditional dish of which country?",
    choices: ["Portugal", "Spain", "Mexico", "Argentina"],
    answerIndex: 1,
  },
  {
    id: "fud-14",
    category: "Food & drink",
    prompt: "What is the main ingredient of a plain omelette?",
    choices: ["Eggs", "Potato", "Flour", "Cheese"],
    answerIndex: 0,
  },
  {
    id: "fud-15",
    category: "Food & drink",
    prompt: "Sake is brewed from which grain?",
    choices: ["Barley", "Rice", "Millet", "Rye"],
    answerIndex: 1,
  },
  {
    id: "fud-16",
    category: "Food & drink",
    prompt: "Hollandaise sauce is an emulsion of butter and what?",
    choices: ["Cream", "Egg yolk", "Flour", "Cheese"],
    answerIndex: 1,
  },
  {
    id: "fud-17",
    category: "Food & drink",
    prompt: "A prune is a dried version of which fruit?",
    choices: ["Grape", "Fig", "Plum", "Apricot"],
    answerIndex: 2,
  },
  {
    id: "fud-18",
    category: "Food & drink",
    prompt: "Which nut is stirred into traditional pesto Genovese?",
    choices: ["Cashew", "Pine nut", "Peanut", "Macadamia"],
    answerIndex: 1,
  },
  {
    id: "fud-19",
    category: "Food & drink",
    prompt: "Cheddar cheese takes its name from a village in which country?",
    choices: ["Ireland", "England", "France", "Netherlands"],
    answerIndex: 1,
  },
  {
    id: "fud-20",
    category: "Food & drink",
    prompt: "Espresso as a coffee style originated in which country?",
    choices: ["Turkey", "Italy", "Brazil", "Austria"],
    answerIndex: 1,
  },
  {
    id: "fud-21",
    category: "Food & drink",
    prompt: "A julienne cut produces vegetables in what shape?",
    choices: ["Cubes", "Thin matchsticks", "Rings", "Wedges"],
    answerIndex: 1,
  },
  {
    id: "fud-22",
    category: "Food & drink",
    prompt: "Natural vanilla comes from the pod of which kind of plant?",
    choices: ["A fern", "An orchid", "A palm", "A cactus"],
    answerIndex: 1,
  },
  {
    id: "fud-23",
    category: "Food & drink",
    prompt: "Which compound makes chilli peppers taste hot?",
    choices: ["Capsaicin", "Piperine", "Allicin", "Menthol"],
    answerIndex: 0,
  },
  {
    id: "fud-24",
    category: "Food & drink",
    prompt: "Sourdough bread is leavened by what?",
    choices: [
      "Baking powder",
      "A wild yeast starter",
      "Bicarbonate of soda",
      "Beaten egg white",
    ],
    answerIndex: 1,
  },

  /* -------------------------------------------------------- language */
  {
    id: "lng-1",
    category: "Language",
    prompt: "How many letters are there in the modern English alphabet?",
    choices: ["24", "25", "26", "27"],
    answerIndex: 2,
  },
  {
    id: "lng-2",
    category: "Language",
    prompt: "What is the Latin-style plural of \"cactus\"?",
    choices: ["Cactuses", "Cacti", "Cactae", "Cactus"],
    answerIndex: 1,
  },
  {
    id: "lng-3",
    category: "Language",
    prompt: "Which language has the most native speakers in the world?",
    choices: ["English", "Spanish", "Hindi", "Mandarin Chinese"],
    answerIndex: 3,
  },
  {
    id: "lng-4",
    category: "Language",
    prompt: "What is a word that reads the same forwards and backwards called?",
    choices: ["Anagram", "Homonym", "Acronym", "Palindrome"],
    answerIndex: 3,
  },
  {
    id: "lng-5",
    category: "Language",
    prompt: "In Spanish, what does \"gracias\" mean?",
    choices: ["Please", "Sorry", "Thank you", "Goodbye"],
    answerIndex: 2,
  },
  {
    id: "lng-6",
    category: "Language",
    prompt: "What does the phrase \"et cetera\" mean?",
    choices: ["And the rest", "For example", "That is", "In place of"],
    answerIndex: 0,
  },
  {
    id: "lng-7",
    category: "Language",
    prompt: "Which of these is NOT a Romance language?",
    choices: ["Portuguese", "Romanian", "German", "Italian"],
    answerIndex: 2,
  },
  {
    id: "lng-8",
    category: "Language",
    prompt: "What is the study of the origins of words called?",
    choices: ["Etymology", "Entomology", "Phonology", "Semantics"],
    answerIndex: 0,
  },
  {
    id: "lng-9",
    category: "Language",
    prompt: "In French, what does \"bonjour\" mean?",
    choices: ["Good night", "Hello", "Excuse me", "See you soon"],
    answerIndex: 1,
  },
  {
    id: "lng-10",
    category: "Language",
    prompt: "Which is the first letter of the Greek alphabet?",
    choices: ["Omega", "Beta", "Alpha", "Delta"],
    answerIndex: 2,
  },
  {
    id: "lng-11",
    category: "Language",
    prompt: "The abbreviation RSVP comes from which language?",
    choices: ["Latin", "French", "Italian", "Spanish"],
    answerIndex: 1,
  },
  {
    id: "lng-12",
    category: "Language",
    prompt: "Which part of speech names an action?",
    choices: ["Noun", "Adjective", "Verb", "Adverb"],
    answerIndex: 2,
  },
  {
    id: "lng-13",
    category: "Language",
    prompt: "Which Japanese script is used mainly for words borrowed from other languages?",
    choices: ["Hiragana", "Katakana", "Kanji", "Romaji"],
    answerIndex: 1,
  },
  {
    id: "lng-14",
    category: "Language",
    prompt: "A word meaning the same as another word is called a what?",
    choices: ["Antonym", "Synonym", "Homophone", "Pronoun"],
    answerIndex: 1,
  },
  {
    id: "lng-15",
    category: "Language",
    prompt: "How many syllables are there in a traditional haiku?",
    choices: ["Twelve", "Fourteen", "Seventeen", "Twenty"],
    answerIndex: 2,
  },
  {
    id: "lng-16",
    category: "Language",
    prompt: "A bibliophile is a lover of what?",
    choices: ["Books", "Maps", "Wine", "Horses"],
    answerIndex: 0,
  },
  {
    id: "lng-17",
    category: "Language",
    prompt: "Braille is a writing system read using which sense?",
    choices: ["Sight", "Hearing", "Touch", "Smell"],
    answerIndex: 2,
  },
  {
    id: "lng-18",
    category: "Language",
    prompt: "Esperanto is best described as what kind of language?",
    choices: [
      "An ancient language",
      "A constructed language",
      "A sign language",
      "A dead language",
    ],
    answerIndex: 1,
  },
  {
    id: "lng-19",
    category: "Language",
    prompt: "What is the dot above a lowercase \"i\" called?",
    choices: ["Tittle", "Serif", "Cedilla", "Umlaut"],
    answerIndex: 0,
  },
  {
    id: "lng-20",
    category: "Language",
    prompt: "In Italian, what does \"ciao\" mean?",
    choices: ["Thank you", "Hello or goodbye", "Sorry", "Please"],
    answerIndex: 1,
  },
];
