import "server-only";

/**
 * The Word Race bank: the words a match may draw, and a clue for each.
 *
 * ## Why this is server-only
 *
 * This file used to argue the opposite -- that a player is shown the scrambled
 * letters anyway, so the bank tells them nothing they cannot already see. That
 * is wrong, and the difference is the whole game: unscrambling is WORK, and
 * this is a race. A player holding the bank does not solve the anagram, they
 * look it up -- one console line asking which of 478 entries is a permutation
 * of what is on screen -- and wins every round of every match, for Gold.
 *
 * A dictionary is a web search away, so this does not make cheating
 * impossible; it makes it something a player has to go and build rather than
 * something already sitting in the page they are playing on. Against a game
 * that settles real currency, that gap is worth the constraint.
 *
 * The constraint is on the import graph, not just this file: nothing under
 * components/ may value-import lib/pvp/word-race.ts either, since it imports
 * this. The two clock constants a board genuinely needs live in
 * lib/pvp/word-race-timing.ts precisely so the board never has to. A stray
 * value import fails the build loudly, which is the point -- silence is what
 * makes a leak expensive.
 *
 * ## The rules every entry obeys, and why each one is a rule
 *
 * - 4-8 letters, lowercase a-z. Shorter than four and the scramble is solved
 *   at a glance; longer than eight and a phone's tile row wraps.
 * - Common and unambiguous. A word a player has to argue with is a word that
 *   cost them real Gold, and there is no appeal.
 * - ONE spelling. Anything that splits British/American (colour, theatre,
 *   yoghurt, aluminium, pyjamas) is left out entirely rather than picked --
 *   the guess check is an exact string match, so the loser of a spelling
 *   argument is whoever learned English somewhere else.
 * - No well-known anagram partner. LISTEN/SILENT, TOWER/WROTE, DIARY/DAIRY,
 *   PRESENT/SERPENT and about twenty more were dropped for this: the engine
 *   has no dictionary and cannot accept an alternate, so a scramble that
 *   happens to spell another real word is a round the player can only lose by
 *   being right. It is a 1-in-n! coincidence per round rather than a
 *   certainty, which is exactly why it would be impossible to reproduce as a
 *   bug report.
 * - No proper nouns and nothing offensive.
 *
 * Roughly 300 entries. Thin banks repeat: at five rounds a match, a 40-word
 * bank would have a regular player recognising the letters instead of solving
 * them, and recognition is not the game.
 */

export interface WordRaceWord {
  /** The solution. Lowercase a-z, 4-8 letters. */
  readonly word: string;
  /**
   * One short nudge, shown alongside the tiles.
   *
   * Deliberately vague rather than a definition -- the clue is there to stop a
   * round stalling out into two players staring at the same seven letters, not
   * to hand it to whoever reads fastest. Kept to one short line for the reason
   * lib/arcade/dealer.ts caps its dealer lines: variable-length prose on a
   * fixed card clips, and this one sits under a tile row on a 390px phone.
   */
  readonly hint: string;
}

export const WORD_RACE_WORDS: readonly WordRaceWord[] = [
  { word: "airport", hint: "Planes come and go" },
  { word: "almond", hint: "Nut in marzipan" },
  { word: "anchor", hint: "Holds a ship in place" },
  { word: "animal", hint: "A living creature" },
  { word: "apple", hint: "Keeps the doctor away" },
  { word: "apron", hint: "Worn while cooking" },
  { word: "arrow", hint: "Fired from a bow" },
  { word: "athlete", hint: "Trains and competes" },
  { word: "attic", hint: "Room under the roof" },
  { word: "autumn", hint: "Season of falling leaves" },
  { word: "avenue", hint: "A wide street" },
  { word: "bakery", hint: "Smells of fresh bread" },
  { word: "balcony", hint: "Step out from an upstairs room" },
  { word: "ballet", hint: "Dancing on your toes" },
  { word: "balloon", hint: "Filled with air and it floats" },
  { word: "bamboo", hint: "Grass a panda eats" },
  { word: "banana", hint: "Peel before eating" },
  { word: "bandage", hint: "Wraps a cut" },
  { word: "banjo", hint: "Plucked with five strings" },
  { word: "barrel", hint: "Wooden and full of cider" },
  { word: "basket", hint: "Woven and carried" },
  { word: "battery", hint: "Stores power" },
  { word: "beach", hint: "Sand beside the sea" },
  { word: "beacon", hint: "A light that warns" },
  { word: "bedroom", hint: "Where you sleep" },
  { word: "beetle", hint: "Insect with a hard shell" },
  { word: "bicycle", hint: "Two wheels and pedals" },
  { word: "birthday", hint: "Comes round once a year" },
  { word: "biscuit", hint: "Snaps when you dunk it" },
  { word: "blanket", hint: "Keeps a bed warm" },
  { word: "blender", hint: "Whizzes up a smoothie" },
  { word: "blossom", hint: "Spring flowers on a tree" },
  { word: "bottle", hint: "Holds a drink" },
  { word: "bracelet", hint: "Worn on the wrist" },
  { word: "branch", hint: "Grows out of a trunk" },
  { word: "breeze", hint: "A gentle wind" },
  { word: "bridge", hint: "Carries a road over water" },
  { word: "brownie", hint: "Chewy chocolate square" },
  { word: "bubble", hint: "Floats until it pops" },
  { word: "bucket", hint: "Carries water" },
  { word: "bunker", hint: "Sand trap on a golf course" },
  { word: "butter", hint: "Spread on toast" },
  { word: "button", hint: "Fastens a shirt" },
  { word: "cabin", hint: "Small wooden house" },
  { word: "cactus", hint: "Spiky desert plant" },
  { word: "camel", hint: "Crosses sand with a hump" },
  { word: "camera", hint: "Takes photos" },
  { word: "candle", hint: "Burns down a wick" },
  { word: "cannon", hint: "Fires a heavy ball" },
  { word: "canvas", hint: "A painter works on it" },
  { word: "canyon", hint: "Deep valley cut by a river" },
  { word: "captain", hint: "Leads the ship" },
  { word: "carnival", hint: "Parade with costumes" },
  { word: "carpet", hint: "Covers a floor" },
  { word: "carrot", hint: "Long orange vegetable" },
  { word: "castle", hint: "Stone walls and a moat" },
  { word: "cattle", hint: "A herd of cows" },
  { word: "ceiling", hint: "Above your head indoors" },
  { word: "chapel", hint: "A small place of worship" },
  { word: "cheese", hint: "Made from milk" },
  { word: "cheetah", hint: "Fastest land animal" },
  { word: "cherry", hint: "Small red fruit with a stone" },
  { word: "chicken", hint: "Farmyard bird" },
  { word: "chimney", hint: "Smoke goes up it" },
  { word: "chorus", hint: "The part everyone sings" },
  { word: "cinema", hint: "Big screen and popcorn" },
  { word: "circle", hint: "Perfectly round" },
  { word: "clever", hint: "Quick to work it out" },
  { word: "cliff", hint: "Steep rock face" },
  { word: "clock", hint: "Tells the time" },
  { word: "clover", hint: "Lucky with four leaves" },
  { word: "cobweb", hint: "Dusty and in a corner" },
  { word: "coffee", hint: "Morning pick-me-up" },
  { word: "comet", hint: "Streaks past with a tail" },
  { word: "compass", hint: "Points north" },
  { word: "cookie", hint: "Baked with chocolate chips" },
  { word: "cottage", hint: "Small country house" },
  { word: "cotton", hint: "Soft fibre in a shirt" },
  { word: "cousin", hint: "Your aunt's child" },
  { word: "cowboy", hint: "Rides with a lasso" },
  { word: "crater", hint: "Left by an impact" },
  { word: "crayon", hint: "Wax stick for drawing" },
  { word: "cricket", hint: "Bat, ball and stumps" },
  { word: "crown", hint: "Worn by a monarch" },
  { word: "crystal", hint: "Clear and sharply cut" },
  { word: "cupboard", hint: "Shelves behind a door" },
  { word: "curtain", hint: "Pulled across a window" },
  { word: "cushion", hint: "Soft to sit on" },
  { word: "cyclone", hint: "A spinning storm" },
  { word: "dancer", hint: "Moves to the music" },
  { word: "daughter", hint: "A parent's girl" },
  { word: "daylight", hint: "The sun is up" },
  { word: "dentist", hint: "Looks after your teeth" },
  { word: "dessert", hint: "The sweet course" },
  { word: "diamond", hint: "Hardest gem" },
  { word: "dinner", hint: "The evening meal" },
  { word: "doctor", hint: "Treats the sick" },
  { word: "dolphin", hint: "Clever sea mammal" },
  { word: "donkey", hint: "Long ears and a bray" },
  { word: "doorway", hint: "You walk through it" },
  { word: "dragon", hint: "Breathes fire in stories" },
  { word: "drum", hint: "Hit to keep the beat" },
  { word: "dungeon", hint: "Cell under a castle" },
  { word: "eagle", hint: "Powerful bird of prey" },
  { word: "eclipse", hint: "The moon blocks the sun" },
  { word: "eleven", hint: "One more than ten" },
  { word: "engine", hint: "Powers a car" },
  { word: "envelope", hint: "Holds a letter" },
  { word: "evening", hint: "After the sun goes down" },
  { word: "fabric", hint: "Cloth on a roll" },
  { word: "factory", hint: "Where things are made" },
  { word: "falcon", hint: "Hunting bird that dives" },
  { word: "farmer", hint: "Works the land" },
  { word: "feather", hint: "Light and from a bird" },
  { word: "ferry", hint: "Carries cars across water" },
  { word: "festival", hint: "Music in a field" },
  { word: "fiddle", hint: "Another name for a violin" },
  { word: "fishing", hint: "Rod, line and patience" },
  { word: "flame", hint: "The bright part of a fire" },
  { word: "flower", hint: "Blooms in a garden" },
  { word: "flute", hint: "Blown across, not into" },
  { word: "fossil", hint: "Ancient bone in rock" },
  { word: "fountain", hint: "Water shoots upward" },
  { word: "freezer", hint: "Colder than the fridge" },
  { word: "fridge", hint: "Keeps the milk cold" },
  { word: "friend", hint: "Someone you like" },
  { word: "frost", hint: "White on the grass at dawn" },
  { word: "galaxy", hint: "Billions of stars" },
  { word: "garage", hint: "Where the car sleeps" },
  { word: "garlic", hint: "Strong-smelling bulb" },
  { word: "gazelle", hint: "Leaps across the plains" },
  { word: "ginger", hint: "Hot root in a curry" },
  { word: "giraffe", hint: "Tallest animal" },
  { word: "glacier", hint: "A river of ice" },
  { word: "glasses", hint: "Worn to see better" },
  { word: "glove", hint: "Fits over your fingers" },
  { word: "goblin", hint: "Small mischievous creature" },
  { word: "golden", hint: "Made of the precious metal" },
  { word: "grape", hint: "Grows in bunches" },
  { word: "gravity", hint: "Pulls everything down" },
  { word: "guitar", hint: "Six strings and a strum" },
  { word: "hammer", hint: "Drives in a nail" },
  { word: "hamster", hint: "Pet with a running wheel" },
  { word: "handle", hint: "Grab it to open the door" },
  { word: "harvest", hint: "Bringing in the crops" },
  { word: "hedgehog", hint: "Prickly and curls into a ball" },
  { word: "helmet", hint: "Protects your head" },
  { word: "hobby", hint: "What you do for fun" },
  { word: "hockey", hint: "Played with a curved stick" },
  { word: "holiday", hint: "Time away from work" },
  { word: "honey", hint: "Made by bees" },
  { word: "horizon", hint: "Where sky meets land" },
  { word: "hospital", hint: "Wards and doctors" },
  { word: "hunter", hint: "Tracks and chases" },
  { word: "hurdle", hint: "Jumped on the track" },
  { word: "igloo", hint: "House built of snow" },
  { word: "island", hint: "Land ringed by sea" },
  { word: "ivory", hint: "Creamy white and from a tusk" },
  { word: "jacket", hint: "A light coat" },
  { word: "jelly", hint: "Wobbles on the plate" },
  { word: "jigsaw", hint: "A thousand pieces" },
  { word: "jockey", hint: "Rides in a race" },
  { word: "journey", hint: "A long trip" },
  { word: "jungle", hint: "Thick tropical forest" },
  { word: "kayak", hint: "Paddled sitting down" },
  { word: "kettle", hint: "Boils the water" },
  { word: "keyboard", hint: "Typed on all day" },
  { word: "kingdom", hint: "Ruled by a monarch" },
  { word: "kitten", hint: "A young cat" },
  { word: "koala", hint: "Clings to a eucalyptus tree" },
  { word: "ladder", hint: "Climb its rungs" },
  { word: "lagoon", hint: "Still water behind a reef" },
  { word: "lantern", hint: "A light you carry" },
  { word: "laptop", hint: "Computer that folds shut" },
  { word: "laughter", hint: "The sound of a good joke" },
  { word: "laundry", hint: "A basket of washing" },
  { word: "lawyer", hint: "Argues your case" },
  { word: "leather", hint: "Boots and belts are made of it" },
  { word: "lemon", hint: "Sour and yellow" },
  { word: "leopard", hint: "Spotted big cat" },
  { word: "letter", hint: "Posted in an envelope" },
  { word: "lettuce", hint: "The leaves in a salad" },
  { word: "library", hint: "Rows and rows of books" },
  { word: "lipstick", hint: "Twists up out of a tube" },
  { word: "lizard", hint: "Scaly and basks in the sun" },
  { word: "llama", hint: "Woolly and spits" },
  { word: "lobster", hint: "Sea creature with claws" },
  { word: "luggage", hint: "Wheeled through an airport" },
  { word: "machine", hint: "Does the work for you" },
  { word: "magnet", hint: "Attracts iron" },
  { word: "magpie", hint: "Black and white thief" },
  { word: "mailbox", hint: "Letters land in it" },
  { word: "mammoth", hint: "Woolly and long extinct" },
  { word: "mansion", hint: "A very large house" },
  { word: "marathon", hint: "Twenty-six miles" },
  { word: "market", hint: "Stalls and shoppers" },
  { word: "mattress", hint: "Sits on the bed frame" },
  { word: "meadow", hint: "Open field of grass" },
  { word: "medal", hint: "Hung round a winner's neck" },
  { word: "memory", hint: "What you can still recall" },
  { word: "mermaid", hint: "Half woman, half fish" },
  { word: "midnight", hint: "Twelve at night" },
  { word: "mirror", hint: "Shows your reflection" },
  { word: "mitten", hint: "Glove with no separate fingers" },
  { word: "moment", hint: "Over in a second" },
  { word: "monkey", hint: "Swings through the trees" },
  { word: "monster", hint: "Hides under the bed" },
  { word: "morning", hint: "Start of the day" },
  { word: "mosaic", hint: "Picture made of tiny tiles" },
  { word: "mosquito", hint: "Bites and whines" },
  { word: "mountain", hint: "Very high ground" },
  { word: "muffin", hint: "Small cake in a paper case" },
  { word: "muscle", hint: "Flexes under the skin" },
  { word: "museum", hint: "Exhibits behind glass" },
  { word: "mushroom", hint: "Grows in damp woods" },
  { word: "music", hint: "Made by instruments" },
  { word: "nature", hint: "The wild world outside" },
  { word: "necklace", hint: "Hangs at the throat" },
  { word: "needle", hint: "Threaded to sew" },
  { word: "nephew", hint: "Your brother's son" },
  { word: "network", hint: "Everything wired together" },
  { word: "nickel", hint: "A five cent coin" },
  { word: "noodle", hint: "Long strand in a soup" },
  { word: "notebook", hint: "Blank pages to fill" },
  { word: "nurse", hint: "Cares for patients" },
  { word: "oatmeal", hint: "Warm bowl on a cold day" },
  { word: "octopus", hint: "Eight arms" },
  { word: "office", hint: "Desks and meetings" },
  { word: "onion", hint: "Chopping it makes you cry" },
  { word: "orange", hint: "Citrus you peel" },
  { word: "orbit", hint: "The path round a planet" },
  { word: "orchard", hint: "Rows of fruit trees" },
  { word: "ostrich", hint: "Runs but cannot fly" },
  { word: "otter", hint: "Playful in the river" },
  { word: "oxygen", hint: "What we breathe in" },
  { word: "oyster", hint: "Might hold a pearl" },
  { word: "packet", hint: "A small parcel" },
  { word: "paddle", hint: "Moves a canoe" },
  { word: "palace", hint: "Grand royal home" },
  { word: "pancake", hint: "Flat, fried and tossed" },
  { word: "panther", hint: "Big cat in the shadows" },
  { word: "pantry", hint: "Where the tins live" },
  { word: "parade", hint: "Marches down the street" },
  { word: "parcel", hint: "Wrapped and delivered" },
  { word: "parsley", hint: "Green herb on a plate" },
  { word: "passport", hint: "Stamped at the border" },
  { word: "pastry", hint: "Rolled out for a pie" },
  { word: "peacock", hint: "Fans out its tail" },
  { word: "peanut", hint: "Grows under the ground" },
  { word: "pearl", hint: "Grown inside a shell" },
  { word: "pebble", hint: "Small smooth stone" },
  { word: "pelican", hint: "Bird with a pouched beak" },
  { word: "pencil", hint: "Write, then rub it out" },
  { word: "penguin", hint: "Swims better than it walks" },
  { word: "pepper", hint: "Shaken beside the salt" },
  { word: "perfume", hint: "A dab behind the ear" },
  { word: "photo", hint: "A moment kept" },
  { word: "piano", hint: "Eighty-eight keys" },
  { word: "picnic", hint: "Lunch on a blanket" },
  { word: "picture", hint: "Framed on the wall" },
  { word: "pigeon", hint: "Struts round the square" },
  { word: "pillar", hint: "Holds up the roof" },
  { word: "pillow", hint: "Rest your head on it" },
  { word: "pilot", hint: "Flies the plane" },
  { word: "pirate", hint: "Sails under a black flag" },
  { word: "planet", hint: "Goes round a star" },
  { word: "plastic", hint: "Cheap and it never rots" },
  { word: "plateau", hint: "High and flat" },
  { word: "plumber", hint: "Comes about the leak" },
  { word: "pocket", hint: "Sewn into a coat" },
  { word: "poetry", hint: "Written in verse" },
  { word: "poison", hint: "Do not drink it" },
  { word: "pony", hint: "A very small horse" },
  { word: "popcorn", hint: "Bursts in the pan" },
  { word: "portrait", hint: "A painting of a person" },
  { word: "poster", hint: "Stuck up on a wall" },
  { word: "potato", hint: "Dug up and mashed" },
  { word: "pottery", hint: "Thrown on a wheel" },
  { word: "prairie", hint: "Wide open grassland" },
  { word: "pretzel", hint: "Salty and knotted" },
  { word: "printer", hint: "Always out of ink" },
  { word: "prison", hint: "Bars and a sentence" },
  { word: "pudding", hint: "What comes after dinner" },
  { word: "puddle", hint: "Left behind by the rain" },
  { word: "pumpkin", hint: "Carved in October" },
  { word: "puppy", hint: "A young dog" },
  { word: "purple", hint: "Between red and blue" },
  { word: "puzzle", hint: "Worked out for fun" },
  { word: "pyramid", hint: "Four sloping sides" },
  { word: "quarry", hint: "Where stone is cut" },
  { word: "rabbit", hint: "Long ears and a hop" },
  { word: "radar", hint: "Finds what you cannot see" },
  { word: "radish", hint: "Peppery and pink" },
  { word: "railway", hint: "Two rails and a sleeper" },
  { word: "rainbow", hint: "Arch of light after a shower" },
  { word: "ranch", hint: "Cattle and wide fences" },
  { word: "raven", hint: "Big black bird" },
  { word: "razor", hint: "Shaves the stubble" },
  { word: "record", hint: "Vinyl on a turntable" },
  { word: "reindeer", hint: "Antlers and a sleigh" },
  { word: "ribbon", hint: "Tied into a bow" },
  { word: "river", hint: "Runs down to the sea" },
  { word: "robot", hint: "Built to do the job" },
  { word: "rocket", hint: "Climbs out of the sky" },
  { word: "rodeo", hint: "Eight seconds on a bull" },
  { word: "rooster", hint: "Crows at dawn" },
  { word: "rubber", hint: "Stretches and bounces" },
  { word: "ruler", hint: "Straight lines and inches" },
  { word: "runway", hint: "Where the plane lands" },
  { word: "saddle", hint: "Sit on it to ride" },
  { word: "safari", hint: "Out looking for lions" },
  { word: "sailor", hint: "Works the deck" },
  { word: "salad", hint: "A bowl of raw leaves" },
  { word: "salmon", hint: "Swims upstream, pink inside" },
  { word: "sandal", hint: "Summer shoe with straps" },
  { word: "sandwich", hint: "Filling between two slices" },
  { word: "sapphire", hint: "Deep blue gem" },
  { word: "saucer", hint: "Sits under the cup" },
  { word: "sausage", hint: "Sizzles in a pan" },
  { word: "scarf", hint: "Wound round the neck" },
  { word: "school", hint: "Lessons and a bell" },
  { word: "scissors", hint: "Two blades and a snip" },
  { word: "scooter", hint: "One foot on, one foot pushing" },
  { word: "sculptor", hint: "Carves a figure out of stone" },
  { word: "seagull", hint: "Steals chips at the coast" },
  { word: "seashell", hint: "Hold it to your ear" },
  { word: "seaside", hint: "Deckchairs and gulls" },
  { word: "seaweed", hint: "Green and slippery on the rocks" },
  { word: "sequin", hint: "Tiny shiny disc on a dress" },
  { word: "serpent", hint: "A snake, in older words" },
  { word: "shadow", hint: "Follows you in the sun" },
  { word: "shampoo", hint: "Lathered into hair" },
  { word: "shark", hint: "A fin above the water" },
  { word: "shelf", hint: "Books stand on it" },
  { word: "shelter", hint: "Somewhere out of the storm" },
  { word: "sheriff", hint: "Wears the star" },
  { word: "shoulder", hint: "Where the arm meets the body" },
  { word: "shovel", hint: "Digs the hole" },
  { word: "shrimp", hint: "Small and pink on a cocktail stick" },
  { word: "sibling", hint: "A brother or a sister" },
  { word: "signal", hint: "Red, amber and green" },
  { word: "silver", hint: "Second place metal" },
  { word: "sketch", hint: "A quick rough drawing" },
  { word: "skiing", hint: "Downhill on two planks" },
  { word: "skyline", hint: "The city against the sky" },
  { word: "sleeve", hint: "Covers your arm" },
  { word: "sleigh", hint: "Pulled over the snow" },
  { word: "slipper", hint: "Soft shoe for indoors" },
  { word: "slogan", hint: "The line in the advert" },
  { word: "slumber", hint: "A deep sleep" },
  { word: "smoke", hint: "Rises off a fire" },
  { word: "snowball", hint: "Packed and thrown" },
  { word: "snowman", hint: "A carrot for a nose" },
  { word: "soccer", hint: "Eleven a side and a round ball" },
  { word: "solar", hint: "Powered by the sun" },
  { word: "soldier", hint: "Serves in an army" },
  { word: "sparrow", hint: "Small brown garden bird" },
  { word: "spider", hint: "Spins a web" },
  { word: "spinach", hint: "Popeye swore by it" },
  { word: "sponge", hint: "Soaks it up in the sink" },
  { word: "spring", hint: "The season after winter" },
  { word: "squirrel", hint: "Bushy tail, buries nuts" },
  { word: "stadium", hint: "Where the crowd sits" },
  { word: "stairs", hint: "Climb between floors" },
  { word: "stallion", hint: "A full-grown male horse" },
  { word: "stamp", hint: "Licked and stuck on a letter" },
  { word: "station", hint: "Wait here for the train" },
  { word: "statue", hint: "A figure carved in stone" },
  { word: "steeple", hint: "Points up from a church" },
  { word: "stencil", hint: "Spray through its cut-out" },
  { word: "stomach", hint: "Where your dinner goes" },
  { word: "storm", hint: "Thunder and heavy rain" },
  { word: "stranger", hint: "Someone you do not know" },
  { word: "student", hint: "Turns up for the lecture" },
  { word: "studio", hint: "Where the record is made" },
  { word: "subway", hint: "The trains run underground" },
  { word: "sugar", hint: "Two spoons in the tea" },
  { word: "summer", hint: "The hottest season" },
  { word: "sunrise", hint: "First light of the day" },
  { word: "sunset", hint: "Last light of the day" },
  { word: "surfing", hint: "Standing up on a wave" },
  { word: "surgeon", hint: "The doctor who operates" },
  { word: "swallow", hint: "Bird that means summer" },
  { word: "swamp", hint: "Wet ground you sink into" },
  { word: "sweater", hint: "Knitted and warm" },
  { word: "swimmer", hint: "Length after length" },
  { word: "syrup", hint: "Poured thick and sweet" },
  { word: "tadpole", hint: "It will be a frog" },
  { word: "tailor", hint: "Measures you for a suit" },
  { word: "tanker", hint: "Ship carrying oil" },
  { word: "teapot", hint: "Short and stout" },
  { word: "temple", hint: "An ancient place of worship" },
  { word: "tennis", hint: "Racket, net and love" },
  { word: "terrace", hint: "A row of joined houses" },
  { word: "thermos", hint: "Keeps the soup hot" },
  { word: "thistle", hint: "Purple, spiky and Scottish" },
  { word: "thumb", hint: "The short fat finger" },
  { word: "thunder", hint: "Follows the flash" },
  { word: "tiara", hint: "A small crown" },
  { word: "ticket", hint: "Gets you in" },
  { word: "tiger", hint: "Striped big cat" },
  { word: "timber", hint: "Cut wood, ready to build" },
  { word: "toast", hint: "Bread that went in the slot" },
  { word: "toffee", hint: "Sticks to your teeth" },
  { word: "tomato", hint: "Red and in the salad" },
  { word: "tongue", hint: "Tastes what you eat" },
  { word: "toolbox", hint: "Spanners live in it" },
  { word: "torch", hint: "A beam in the dark" },
  { word: "tortoise", hint: "Slow, with a hard shell" },
  { word: "tourist", hint: "Camera and a map" },
  { word: "towel", hint: "Dries you off" },
  { word: "tractor", hint: "Big wheels on a farm" },
  { word: "traffic", hint: "Cars going nowhere" },
  { word: "treasure", hint: "Buried, with a map" },
  { word: "tricycle", hint: "Three wheels" },
  { word: "trolley", hint: "Pushed round the supermarket" },
  { word: "trophy", hint: "Lifted by the winner" },
  { word: "trousers", hint: "Two legs and a belt" },
  { word: "truck", hint: "Hauls the load" },
  { word: "trumpet", hint: "Brass, with three valves" },
  { word: "tulip", hint: "Spring bulb from Holland" },
  { word: "tunnel", hint: "Cut straight through the hill" },
  { word: "turkey", hint: "The Christmas bird" },
  { word: "turtle", hint: "Swims with a shell" },
  { word: "tuxedo", hint: "Black tie and a jacket" },
  { word: "twilight", hint: "Between sunset and dark" },
  { word: "typhoon", hint: "A tropical storm" },
  { word: "umbrella", hint: "Keeps the rain off" },
  { word: "unicorn", hint: "One horn, all myth" },
  { word: "uniform", hint: "Everyone wears the same" },
  { word: "vacuum", hint: "Sucks up the crumbs" },
  { word: "valley", hint: "Low ground between hills" },
  { word: "vampire", hint: "Sleeps until dark" },
  { word: "vanilla", hint: "The plainest ice cream" },
  { word: "velvet", hint: "Soft and deep to the touch" },
  { word: "vendor", hint: "Sells from a stall" },
  { word: "vessel", hint: "A boat, in formal words" },
  { word: "viking", hint: "Longship raider" },
  { word: "village", hint: "Smaller than a town" },
  { word: "vinegar", hint: "Sharp on the chips" },
  { word: "violet", hint: "Small purple flower" },
  { word: "violin", hint: "Played with a bow" },
  { word: "volcano", hint: "Erupts with lava" },
  { word: "voyage", hint: "A long trip by sea" },
  { word: "waffle", hint: "Squares under the syrup" },
  { word: "wagon", hint: "Pulled behind the horses" },
  { word: "waiter", hint: "Brings your order" },
  { word: "wallet", hint: "Folds round your cards" },
  { word: "walnut", hint: "Nut in a wrinkled shell" },
  { word: "walrus", hint: "Tusks and whiskers" },
  { word: "wardrobe", hint: "Where the clothes hang" },
  { word: "watch", hint: "The clock on your wrist" },
  { word: "weasel", hint: "Long, thin and quick" },
  { word: "weather", hint: "Rain or shine" },
  { word: "wedding", hint: "Two people marry" },
  { word: "welder", hint: "Joins metal with sparks" },
  { word: "whale", hint: "Biggest animal in the sea" },
  { word: "wheat", hint: "Ground into flour" },
  { word: "wheel", hint: "Round, and it turns" },
  { word: "whisper", hint: "Said very quietly" },
  { word: "whistle", hint: "Blown to stop the game" },
  { word: "wildlife", hint: "The animals out there" },
  { word: "willow", hint: "Tree that weeps" },
  { word: "windmill", hint: "Four sails going round" },
  { word: "window", hint: "Look out through it" },
  { word: "winter", hint: "The coldest season" },
  { word: "wisdom", hint: "What the years teach" },
  { word: "wizard", hint: "Casts the spells" },
  { word: "wonder", hint: "What amazement feels like" },
  { word: "woodland", hint: "Trees, but not a forest" },
  { word: "workshop", hint: "Bench, vice and sawdust" },
  { word: "wrench", hint: "Turns a stubborn nut" },
  { word: "wrist", hint: "Between hand and arm" },
  { word: "writer", hint: "Fills the blank page" },
  { word: "yacht", hint: "Sails, and it is expensive" },
  { word: "yellow", hint: "The shade of a lemon" },
  { word: "zebra", hint: "Striped like a crossing" },
  { word: "zipper", hint: "Pulled up to close a coat" },
];

/** The bounds every entry is checked against, and the tile row is sized for. */
export const WORD_RACE_MIN_LENGTH = 4;
export const WORD_RACE_MAX_LENGTH = 8;
