/**
 * The wardrobe catalogue, generated by the art pipeline
 * (art/stackacres-td/lpc/wardrobe.py). One import for the server's checks and
 * the editor alike; ./catalogue.test.ts holds the file to the WardrobeCatalogue shape.
 */

import generated from "@/public/stackacres-td/wardrobe/catalogue.json";
import type { WardrobeCatalogue } from "./types";

export const WARDROBE_CATALOGUE: WardrobeCatalogue = generated as WardrobeCatalogue;
