/**
 * The farmer's look: what the player picked at the mirror, as catalogue ids.
 *
 * The catalogue itself is generated by the art pipeline
 * (art/stackacres-td/lpc/wardrobe.py writes public/stackacres-td/wardrobe/
 * catalogue.json) so the ids here can only be ones the art exists for. The
 * sheet is baked from a look in the browser (./bake.ts) with the same shrink
 * the shipped cast uses, so the default look is pixel-identical to
 * public/stackacres-td/characters/farmer.png.
 */

export type WardrobeBody = "male" | "female";

/** The parts a look is made of, in the order the editor shows them. */
export const WARDROBE_SLOTS = ["skin", "eyes", "hair", "hat", "top", "over", "bottom", "shoes", "face"] as const;
export type WardrobeSlot = (typeof WARDROBE_SLOTS)[number];

/** Slots a look may leave empty. */
export const OPTIONAL_SLOTS: readonly WardrobeSlot[] = ["hat", "over", "face"];

/** One pick: an item and the colour it is worn in. `item` null is "none" for an optional slot. */
export interface WardrobePick {
  readonly item: string | null;
  readonly colour: string | null;
}

export interface FarmerLook {
  readonly body: WardrobeBody;
  readonly picks: Readonly<Record<WardrobeSlot, WardrobePick>>;
}

/** Saved outfits at the mirror. */
export const OUTFIT_SLOTS = 4;

/** What is stored per profile (profiles.avatar_config.farmer). */
export interface FarmerWardrobeState {
  readonly look: FarmerLook;
  /** Saved outfits, null for an empty slot. Always OUTFIT_SLOTS long. */
  readonly outfits: readonly (FarmerLook | null)[];
}

/** One colour a catalogue item can be worn in. */
export interface WardrobeColour {
  readonly id: string;
  readonly label: string;
  /** The swatch the editor shows, "#rrggbb". */
  readonly swatch: string;
}

/** One pickable item. */
export interface WardrobeItem {
  readonly id: string;
  readonly slot: WardrobeSlot;
  readonly label: string;
  /** Which bodies it is drawn for. */
  readonly bodies: readonly WardrobeBody[];
  /** Colour ids it can be worn in; the first is its default. Empty for items with fixed colours. */
  readonly colours: readonly string[];
  /** Null: free to everyone. A number: Gold to buy it once, after which it is owned. */
  readonly price: number | null;
}

/** The generated catalogue (public/stackacres-td/wardrobe/catalogue.json), as the app reads it. */
export interface WardrobeCatalogue {
  readonly version: number;
  readonly items: readonly WardrobeItem[];
  /** Colour ids by palette, e.g. skin, hair, eye, cloth. */
  readonly colours: Readonly<Record<string, WardrobeColour>>;
  /** Today's farmer, exactly. */
  readonly defaultLook: FarmerLook;
}
